### ISSUE TITLE
Document installation process on windows

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#1]
[psql2csv](https://github.com/fphilipe/psql2csv) is listed as a requirement and is available on [Homebrew ](https://brew.sh/).

I am currently on a windows machine. 

[Homebrew 2.0.0](https://brew.sh/2019/02/02/homebrew-2.0.0/) documentation indicates that homebrew officially supports Linux and Windows 10 with Windows Subsystem for Linux (WSL).  

Do you think this is the way to go and if so do you think that the other requirements - bcfishobs, bcdata and pgdata should be loaded into a conda env that is loaded inside of a WSL as per https://gist.github.com/kauffmanes/5e74916617f9993bc3479f401dfec7da ?

**Comment by smnorris** [comment]
A few things:
- this repo is a work in progress, requirements list isn't complete or checked
- psql2csv is not essential, I find it handy for quick reporting
- I think WSL would be a good way to go for these scripts on windows, then you wouldn't have to modify them then (although modifications should mostly just be the line ending characters)
- I haven't tried homebrew on WSL, but that is a good way to grab any other requirements not on the system (like wget)
- conda probably isn't necessary if using WSL, I think rasterio/gdal/geopandas should all just work with pip - but using a conda env is a good idea

**Comment by smnorris** [comment]
Looks like I can't easily test WSL. My windows install is on a VM, running the linux VM inside the windows VM might be possible but takes some setup - https://github.com/microsoft/WSL/issues/4120

**Comment by smnorris** [comment]
This seems to work fine for getting started on a fresh WSL (Ubuntu 20.04.1 LTS). Not sure I would bother installing homebrew, conda should do the job - just ignore the psql2csv requirement for now.

```
sudo apt update
sudo apt upgrade
sudo apt install python3 python3-pip
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
# follow instructions, accept terms, restart terminal

conda create -n geo_env
conda activate geo_env
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install gdal
conda install geopandas
conda install rasterio
pip3 install bcdata
```
