### ISSUE TITLE
utmzone function not available

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#103]
Getting the following error running `02_model/crossing_update.sh`

```
psql:sql/crossings.sql:237: ERROR:  function utmzone(geometry) does not exist
LINE 64:     SUBSTRING(to_char(utmzone(e.geom),'999999') from 6 for 2...
```

is there a package we need for this that is not named as a requirement yet perhaps?

**Comment by smnorris** [comment]
That is my own function. I added it somewhere...

**Comment by smnorris** [comment]
It should be in there if you've already run '02_model/model.sh`: https://github.com/smnorris/bcfishpass/blob/main/02_model/model.sh#L8

`02_model/crossing_update.sh` might still be ok but I haven't been using it lately - it needs more attention as per https://github.com/smnorris/bcfishpass/issues/8. Until I get a chance to do that I've been doing full runs of `model.sh`
