### ISSUE TITLE
_belowupstreambarriers_ calculations

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#104]
If there are no upstream anthropogenic barriers, the calculation fails and returns a NULL.
Either set default value to the total length/area upstream and UPDATE with the _belowupstreambarriers_ calculation or tweak the query.

**Comment by smnorris** [comment]
I've reloaded `bcfishpass.crossings` to the cwf db with the fix.
Re-run `python bcfishpass.py report bcfishpass.crossings aggregated_crossings_id bcfishpass.barriers_anthropogenic dnstr_barriers_anthropogenic` if you want to fix locally.

**Comment by NewGraphEnvironment** [comment]
I don’t think I am privileged to run with discharges but I can use bcbarriers to update the report in the interim. Thanks Simon
