### ISSUE TITLE
Cumulative elevation above specified elevation threshold as indicator of precip as snow thus channel width and discharge

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#109]
Hi Simon,

I am trying to pull out an elevation for each stream segment.  Can you peak at this when you get a chance and let me know what need to change for it to work? https://github.com/NewGraphEnvironment/bcfishpass/blob/newgraph/01_prep/04_channel_width/sql/channel_width_measured.sql

it says:

`psql:sql/channel_width_measured.sql:177: ERROR:  column "b.geom" must appear in the GROUP BY clause or be used in an aggregate function
LINE 10:     ST_Z (ST_PointN (b.geom, - 1)) as elevation `

**Comment by NewGraphEnvironment** [comment]
got it.  Like it said - add b.geom to the GROUP BY clause...

I'm going to leave this open though because maybe its a nice spot to mention a potential enhancement wish that would have us sample the provincial DEMs for cumulative percentages above specified elevations (ex. 1500m) as an indication of precip as snow.  In a perfect world we might be able to specify the elevation dynamically so that it could be linked to latitudes/longitudes

**Comment by smnorris** [comment]
I'm thinking this would be a better fit in `fwapg`, it is much the same as https://smnorris.github.io/fwapg/03_tables.html#fwa-watersheds-upstream-area
