### ISSUE TITLE
add regional engineering information to database

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#113]
We have a couple of kml layers of the Coastal Bridge Registry (Nadina and Skeena Stikine) from Steve Page that show structures >2m such as major culverts and bridges.  

Wondering how @smnorris might want to incorporate this info into `bcfishpass` .  There is extremely useful info here such as unique identifiers that can be used to tie `modelled_crossing_id`  to `Structure #`  and little beautiful details such as 
`Structure Type/Class` = `Permanent Bridge` and 
`Structure Type/Class` = `Major Culvert`

Building connections with the people that manage these databases is a logical step as it would be great for us to develop methods to pull the latest data raw at regular intervals so things stay up to date.

**Comment by NewGraphEnvironment** [comment]
I’ll ask Steve again for a contact and @jessefraser might be a good Coastal connect to wrangle in on this too actually...

**Comment by smnorris** [comment]
Couple of options:

A. Just flag known bridges by incorporating this as additional source in here:
https://github.com/smnorris/bcfishpass/blob/main/01_prep/01_modelled_stream_crossings/sql/08_identify_open_bottom_structures.sql

B. Treat it like PSICS and use it as a replacement for the modelled crossing in the crossing table. 

Probably not much difference either way but my preference would be for B if the data is good enough.

**Comment by NewGraphEnvironment** [comment]
🚤

**Comment by jessefraser** [comment]
@smnorris and @NewGraphEnvironment shoot me an email, and I can try to connect you to Coast Mountains district folks to see what they have for culverts.

**Comment by NewGraphEnvironment** [comment]
Thanks Jesse.  Steve Page has forwarded along kmls for Nadina, Coast and Skeena-Stikine. We had a good conversation a couple days ago as well about looking at options for best ways forward for sharing info and keeping data formats as raw as possible. I will keep you in the loop.

**Comment by smnorris** [comment]
@NewGraphEnvironment @jessefraser  Any feedback on this? Nothing urgent, only asking because I'm closing a bunch of other issues.

**Comment by smnorris** [comment]
@NewGraphEnvironment @jessefraser 
Going to close this. 
Currently, additional crossing info can be added via the various csv data files.

**Comment by NewGraphEnvironment** [comment]
Prince george district jackpot kmz direct from here

https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/natural-resource-use/resource-roads/local-road-safety-information/prince-george/dpg_roads__bridges.kmz

**Comment by smnorris** [comment]
Great - presuming that every point in the kmz is a bridge, we could use this as a one time QA tool for finding bridges mis-classified as culverts. 

The inspection info in that file is interesting - I expect planning could be easier if we were able to link bcfishpass to existing infrastructure asset management databases :(
