### ISSUE TITLE
Add measured and modelled channel width where we have them

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#116]
Not sure why channel widths for 1st order streams are excluded.  Especially if we have a measured width.  I think perhaps we usually don't have `upstream_area_ha` data for first order streams anyway so no model output at this point anyway... I have a commit that I will reference this with in case it is a change that makes sense.

**Comment by smnorris** [comment]
>>> I think perhaps we usually don't have upstream_area_ha data for first order streams anyway

Exactly

**Comment by smnorris** [comment]
covered by #118
