### ISSUE TITLE
Add PCIC discharge data where available and evaluate suitability for habitat model

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#126]
Modelled discharge (baseflow + surface runoff) is available for Fraser, Columbia and Peace basins from PCIC:
https://pacificclimate.org/data/gridded-hydrologic-model-output

Instructions to generate a discharge raster from @haileye:

> 1. Download Historical -> PNWNAmetbase BASEFLOW & SURFACE RUNOFF netcdf timeseries cubes from PCIC's data portal with a filter from 1981-01-01 to 2010-12-31
https://data.pacificclimate.org/portal/hydro_model_out/map/
>
> 2. Process into a flat raster of MAD in mm using CDO (Climate Data Operators) 
>
>      -- generate the yearly sum of daily records, then take the average of all the years
>      cdo -O -b F64 -timmean -yearsum allwsbc.TPS_gridded_obs_init.1945to2099.BASEFLOW.nc.nc allwsbc.TPS_gridded_obs_init.1980to2010.BASEFLOW_yearsum_mean.nc
>      
 >     cdo -O -b F64 -timmean -yearsum allwsbc.TPS_gridded_obs_init.1945to2099.RUNOFF.nc.nc allwsbc.TPS_gridded_obs_init.1980to2010.RUNOFF_yearsum_mean.nc
 >     
 >     -- add the files together
 >     cdo -b F64 add allwsbc.TPS_gridded_obs_init.1980to2010.BASEFLOW_yearsum_mean.nc allwsbc.TPS_gridded_obs_init.1980to2010.RUNOFF_yearsum_mean.nc B_R_1980to2010_yearsum_mean.nc

**Comment by smnorris** [comment]
Download commands:
```
wget -O baseflow.nc https://data.pacificclimate.org/data/hydro_model_out/allwsbc.TPS_gridded_obs_init.1945to2099.BASEFLOW.nc.nc?BASEFLOW[13149:24105][][]
wget -O runoff.nc https://data.pacificclimate.org/data/hydro_model_out/allwsbc.TPS_gridded_obs_init.1945to2099.RUNOFF.nc.nc?RUNOFF[13149:24105][][]
```

**Comment by NewGraphEnvironment** [comment]
🥇

**Comment by smnorris** [comment]
This is hopefully complete with https://github.com/smnorris/bcfishpass/commit/c62096611b99fbcb517f3686925ba909b1d18f20 - the output for LNIC is a match to what Foundry provided for LNIC. 
Note that there is no currently no check of model output against stream gauges.
