### ISSUE TITLE
Provide foundry schema and fwa_streams_mad table as required to run a channel width model

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#139]
Although discharge values are not required for channel width model runs the mad table is.

I have a PR that attempts to address this.

**Comment by smnorris** [comment]
Makes sense. 
Ideally all discharge would go to a `bcfishpass.fwa_streams_mad` or similar, but that makes sharing the bcfishpass schema tricky. An empty `foundry.fwa_streams_mad` should be fine as a workaround.
