### ISSUE TITLE
`bcfishpass.crossings` table has `utm_easting` sometimes switched with `utm_northing` 

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#153]
If you were to pull these `modelled_crossing_id` from `crossings` you will see which ones have switched columns.  Not really an issue for anything I am doing but thought you would like to know.  My last run was a while back so maybe this has been addressed...

`1805665, 1800752, 1801969, 1803682, 1802760, 1800045, 1800167, 24704566, 1802044, 1802089, 1804694, 1800050, 1802088, 1803403, 1805553, 1805532, 1800062, 1801773, 1801122, 1800060, 1801133, 1800213, 1800422, 1805529, 1802106, 1802820, 24703647, 1800355`

**Comment by smnorris** [comment]
The columns are in the wrong order on the insert, all modelled crossings will have this issue:
https://github.com/smnorris/bcfishpass/blob/main/02_model/sql/crossings.sql#L613

**Comment by smnorris** [comment]
Thanks for catching & reporting!
