### ISSUE TITLE
user data / lookup tables - restructure

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#179]
PSCIS fixes include 'NOT ACCESSIBLE' etc - as per @captainmarmot these don't make sense from a PSCIS user perspective, some normalization of the data tables would be valuable

**Comment by smnorris** [comment]
RE `bcfishpass.pscis_barrier_result_fixes` and `bcfishpass.crossings`:

We have to be able to modify PSCIS barrier status: 
- data/reports/maps all need to be updated for planning well before PSCIS submissions eventually work their way in
- in PSCIS, `crossing_subtype_code = FORD` always translates into `barrier_result_description = UNKNOWN` - this  is not super helpful for planning if it is known to be passable or a barrier (barriers are unlikely but a ford with debris or other issues can occur)

I am thinking some more data could be added to the crossings table:
- `pscis_barrier_result_description` so it is obvious what the actual PSCIS data is
- `pscis_barrier_result_score` just for convenience

If `barrier_status` != `pscis_barrier_result_description`, the user is alerted that the status has been modified by the lookup. Does this seem workable?

**Comment by smnorris** [comment]
Also regarding `bcfishpass.pscis_barrier_result_fixes`:
- move `NOT ACCESSIBLE` to a different, separate table, this is just a barrier status control table not a habitat control table
- consider renaming table to something that clearly indicates it is a user tweaks to `crossings.barrier_status`
- check that all records in the table are actually doing something - remove any that match the current PSCIS result

**Comment by NewGraphEnvironment** [comment]
> * in PSCIS, `crossing_subtype_code = FORD` always translates into `barrier_result_description = UNKNOWN` - this  is not super helpful for planning if it is known to be passable or a barrier (barriers are unlikely but a ford with debris or other issues can occur)

In my experience - for field survey purposes - it is very unlikely that a ford is not passable and they should be symbolized on field maps as "other". When we come across points symbolized as "passable" in the field we think that the status of the crossing has changed (ie. bridge was removed) so we reassess the crossing.  

In summary, for connectivity planning assigning fords a passable status seems very reasonable but for the creation of field maps the fords need to be identified so that the status of the crossing in PSCIS is certain.

**Comment by smnorris** [comment]
Proposed updated "definite barrier" user control table structure:

```
barrier_type
barrier_name
barrier_ind
blue_line_key
downstream_route_measure
watershed_group_code
review_name
review_date
review_notes
```

By editing this table, user can
- add new barriers 
- remove/disable existing barriers by adding a record that sets the `barrier_ind` status to `False` 

A single 'barriers_definite.csv` can combine existing:
- exclusions.csv
- falls_barrier_ind.csv
- falls_other.csv
- gradient_barriers_passable.csv
- misc_barriers_definite.csv
- NOT ACCESSIBLE records from pscis_barrier_result_fixes

PSCIS/anthropogenic barrier control table would be separate.

In theory, column/columns could be added to add/control barriers per species/species scenario but that can wait until somebody asks for it.

**Comment by smnorris** [comment]
Not quite as clean as I'd like it - it doesn't make sense to include `falls_other.csv` because we are tracking falls that are not actually barriers.
