### ISSUE TITLE
Is it possible to avoid creating yet another crossings id column?

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#18]
Crossings come from 3 sources:
1. modelled crossings
2. PSCIS
3. dams

Because each source has its own set of ids, we create a new `aggregated_crossings_id` column for the crossings table. This is generally fine because the source `modelled_crossing_id`, pscis `crossing_id` and `dam_id` are kept. But for the `dnstr_crossings` and `dnstr_barriers_anthropogenic` columns it would be much nicer to use the source ids for clarity. Plus yet another crossing id column gets even more confusing.

There shouldn't be much/any overlap in the id values - perhaps there is a way to combine them into the `aggregated_crossings_id` without changing them? 

Or simply create a primary key based on all three columns? This might work in the db but will not work for QGIS or other tools which need a single unique id

**Comment by smnorris** [comment]
Maybe the simplest thing to do is make `aggregated_crossings_id` a text column with values like this:
`PSCIS_12345`, `PSCIS_4567`, `MODEL_2345`, `DAM_654` etc

**Comment by smnorris** [comment]
Currently:

```
postgis=# select max(stream_crossing_id) from whse_fish.pscis_assessment_svw;
  max
--------
 197669
(1 row)

postgis=# select min(modelled_crossing_id) from bcfishpass.modelled_stream_crossings;
  min
--------
 100000
```

**Comment by smnorris** [comment]
We could safely ignore this issue if it was just clarity, the extra id to handle isn't too big a deal.
The main usability problem is that because the crossings table and its serial pk gets re-created with each re-run of the model... so the ids change with each re-run.

**Comment by smnorris** [comment]
To fix, while still staying within the integer type bounds(-2147483648 to +2147483647)

- use PSCIS `stream_crossing_id` values as is
- add 1B to `modelled_crossing_id` values
- add 2B to `dam_id` values

With this method we have:
- unique integer ids
- easy to see which source the point is from in the downstream / upstream fields
- support for 8 other potential crossing types, which seems like more than enough, any additional types can likely just be combined into a single 'other' table anyway

**Comment by NewGraphEnvironment** [comment]
Nice work.  

The 32bit integer thing is interesting. I thought it was R specific.  Relieved it is not.  I ran into an issue with one of my date type field assigned ids (YYYYMMDD plus 100 series integer) in the fall and needed to change it to a 10 series after the fact (ie. 20210119101 is not viable where as 2021011910 works).

**Comment by smnorris** [comment]
👍 
Postgres has `bigint` but I'm not sure the `intarray` extension supports them.
I'm still not really using the intarray extension anywhere but want to keep it in mind, it should make searching/joining the columns with lists of ids super quick.

**Comment by NewGraphEnvironment** [comment]
interesting. Unfortunate R situation. 

Hmmm. Are we really close to the max int (2.14B) with 2B and have only 2.1B for another series or are additional potential  int series maybe expected to be relatively small so it’s no big dealio?

**Comment by smnorris** [comment]
I think we are pretty safe with integers 2B-2147483647 to support dams and any additional misc crossings that might come up. If any additional crossing types do come up I could start as low as 2,000,100,000 for new series - not likely to be many more dams added.

**Comment by smnorris** [comment]
We could always go negative too!

**Comment by NewGraphEnvironment** [comment]
mind blown
