### ISSUE TITLE
mapping - QGIS PSCIS symbology for "potential" and "other"

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#180]
Looks to be some symbology mismatched showing up on both the [Elk and Bulkley map outputs](https://hillcrestgeo.ca/outgoing/fishpassage/projects/).  This can lead to misallocated field time.

My assumption is that these maps were generated with the [QGIS lyr file](https://github.com/NewGraphEnvironment/bcfishpass/tree/main/03_mapping/qgis)....

Seems as though in the Elk there is a consistent rendering of all "ford" crossings as "barrier" and in the Bulkley below are examples of mismatches:

PSCIS 
124436 - "potential" but symbolized as "other" [93M.107](https://hillcrestgeo.ca/outgoing/fishpassage/projects/bulkley/FishPassage_093M.107.pdf)

**Comment by smnorris** [comment]
I will check the QGIS files but expect that this is a data issue not a symbology issue.

Elk:
CWF tech misclassified some `crossing_sybtype_code = FORD` features as `barrier_status = BARRIER`. I believe this has been resolved in the data - the maps were probably produced when the error was still present. This is worth double checking though.

Bulkley:
This is the current status of those crossings :
```
 stream_crossing_id | crossing_source | crossing_feature_type | pscis_status | barrier_status | crossing_type_code | crossing_subtype_code 
--------------------+-----------------+-----------------------+--------------+----------------+--------------------+-----------------------
              58182 | PSCIS           | ROAD, RESOURCE/OTHER  | ASSESSED     | PASSABLE       | OTHER              | FORD
              58189 | PSCIS           | ROAD, RESOURCE/OTHER  | ASSESSED     | BARRIER        | CBS                | ROUND
             124436 | PSCIS           | ROAD, RESOURCE/OTHER  | ASSESSED     | POTENTIAL      | CBS                | ROUND
```

This relates back to #179 raised by @captainmarmot this week - the user table `pscis_barrier_result_fixes.csv` is not very clear to PSCIS users and needs cleanup or at least some clear documentation. bcfishpass.crossings rules are not the same as PSCIS - in PSCIS, all Fords have the same results:
```
select distinct crossing_type_code, crossing_subtype_code, barrier_result_description from whse_fish.pscis_assessment_svw where crossing_subtype_code = 'FORD'
 crossing_type_code | crossing_subtype_code | barrier_result_description 
--------------------+-----------------------+----------------------------
 OTHER              | FORD                  | Unknown
```
But in bcfishpass, a ford can be set as whatever we want via the result fixes table.
This may be good for CWF WCRP analysis but for other PSCIS users it is very confusing.

**Comment by smnorris** [comment]
124436 does not seem to be a data issue.

**Comment by NewGraphEnvironment** [comment]
> Bulkley: This is the current status of those crossings :
> 
> ```
>  stream_crossing_id | crossing_source | crossing_feature_type | pscis_status | barrier_status | crossing_type_code | crossing_subtype_code 
> --------------------+-----------------+-----------------------+--------------+----------------+--------------------+-----------------------
>               58182 | PSCIS           | ROAD, RESOURCE/OTHER  | ASSESSED     | PASSABLE       | OTHER              | FORD
>               58189 | PSCIS           | ROAD, RESOURCE/OTHER  | ASSESSED     | BARRIER        | CBS                | ROUND
>              124436 | PSCIS           | ROAD, RESOURCE/OTHER  | ASSESSED     | POTENTIAL      | CBS                | ROUND
> ```

Which table is this referenceing?

124436 does not seem to match what we see on the mapped example I don't think

Looks like many errors are still in the `pscis_barrier_result_fixes.csv` file.  I will document our reassessed Fords here for now.


50174
50173
50175
50076
50092
61636
62159
50151
50208

**Comment by smnorris** [comment]
Symbology definition for `Crossings - Steelhead` layer is indeed incorrect for all 'Unknown's in the Bulkley QGIS file.

**Comment by smnorris** [comment]
QGIS issue is easily fixed but the data issue is trickier.

We have to be able to modify PSCIS barrier status: 
- data/reports/maps all need to be updated for planning well before PSCIS submissions eventually work their way in
- in PSCIS, `crossing_subtype_code = FORD` always translates into `barrier_result_description = UNKNOWN` - this  is not super helpful for planning if it is known to be passable or a barrier (barriers are unlikely but a ford with debris or other issues can occur)

I am thinking some more data could be added to the crossings table:
- `pscis_barrier_result_description` so it is obvious what the actual PSCIS data is
- `pscis_barrier_result_score` just for convenience

If `barrier_status` != `pscis_barrier_result_description`, the user is alerted that the status has been modified by the lookup. Does this seem workable?

**Comment by NewGraphEnvironment** [comment]
> * in PSCIS, `crossing_subtype_code = FORD` always translates into `barrier_result_description = UNKNOWN` - this  is not super helpful for planning if it is known to be passable or a barrier (barriers are unlikely but a ford with debris or other issues can occur)

For field survey purposes, fords should be symbolized on field maps as "other". Because when surveyors come across points symbolized as "passable" in the field they may think that the status of the crossing has changed (ie. bridge was removed) so time is spent reassessing the crossing.  

In summary, for connectivity planning, assigning fords a passable status is reasonable (fords are always passable in my experience) but for the creation of field maps the fords need to be identified so that the status of the crossing in PSCIS is certain for the fieldmap user.

**Comment by smnorris** [comment]
this has been fixed
