### ISSUE TITLE
pscis_modelledcrossings_streams_xref QA

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#19]
PSCIS assessed crossings are not getting matched to nearby modelled crossings because of empty `modelled_crossing_id` values in the xref. 

Fix may require some manual QA but a query on nearby modelled crossings (instream within 100m or so) should identify most and be fairly easy to fix. 

Alternatively changing the logic in the matching is possible... but I think this xref should explicitly match pscis crossings to modelled crossings where possible, not just streams. When `modelled_crossing_id` is null in the xref it should be fairly safe to conclude that there is no mapped road at this location.

**Comment by smnorris** [comment]
Note that there are currently 1844 records without a `modelled_crossing_id`, 1650 with - hopefully most of these 1850 are very close to a modelled crossing.

**Comment by smnorris** [comment]
Not really a bug but this is an important data fix

**Comment by NewGraphEnvironment** [comment]
Definitely an important data fix.  FYI, when I am reviewing pscis crossings to scope for which crossings are good candidates for phase 2 I am populating a  `modelled_crossing_id_corr` column with the associated `modelled_crossing_id` when it appears obvious that they are a match. I will submit match correction table as a pull request eventually. 

It has been common for PSCIS and modelled crossings to be very close together but not matched which obviously would have allowed them to slip through habitat/species based queries. These crossings were flagged for review in my work as potential good bets through PSICS based queries (i.e. high `habitat_value_code `rating or large `downstream_channel_width`,  etc) and not bcfishpass.

**Comment by smnorris** [comment]
Please do. 
I've made an automated fix based on distance for many of them. And CWF has reviewed a bunch more that weren't as close.. I haven't applied all of that fix yet, and there is also the handful of crossings that will take the most time where it really isn't clear what is going on.

**Comment by smnorris** [comment]
This should be fixed now

**Comment by NewGraphEnvironment** [comment]
I ahve a csv with a few crossings that I matched.   Apparently, I can't attach a csv here.  This is what it looks like.  Let me know the best way to do this.  There should maybe be a bunch more for the Bulkley unless they are already dealt with. I'm about to have a look now as it makes the reporting easier when I can match the hab con sites to `bcfishpass` outputs.  Do you know if anyone else is already working on that?

stream_crossing_id	modelled_crossing_id	linear_feature_id	reviewer	notes
50095	4605747	706880116	AI	Very little potential habitat upstream for cutthrout (>25% in 25m).
50090	4602849	706879645	AI	If this is the mainstem, habitat upstream at bridge appears mod to high value.
50110	4605506	706872809	AI	No habitat modelled upstream

**Comment by smnorris** [comment]
Some of them should be dealt with by #60 - I haven't pushed the result of that to the CWF db yet though, I'll do that now. It looks like those three are missed though, add them to `pscis_modelledcrossings_streams_xref.csv` to force the match, but leave out `linear_feature_id` if you are matching to a modelled crossing, it isn't needed. I added some bare bones doc here on how the lookup works https://github.com/smnorris/bcfishpass/tree/main/01_prep/02_pscis

**Comment by NewGraphEnvironment** [comment]
hmm.  should I append to pscis_modelledcrossings_streams_xref.csv and burn a copy to the ali schema?

**Comment by NewGraphEnvironment** [comment]
never mind. i see it now. incoming pr

**Comment by smnorris** [comment]
Very open to different workflow suggestions but I am liking this for tracking changes to the lookup.

**Comment by smnorris** [comment]
Presuming we stick with this I'm already thinking I'll move all the data into one spot so it is front and centre in the repo and more obvious where edits should be made. https://github.com/smnorris/bcfishpass/issues/48

**Comment by NewGraphEnvironment** [comment]
seems like a great workflow to me.  I can see why you put those files there in the first place but everything in one pile might be nice too
