### ISSUE TITLE
wct_lakereservoir_ha included in habitat potential summaries

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#193]
Juvenile and adult WCT use lakes and beaver ponds for overwintering, cover, feeding and movement.  See [reference](https://wildlife-species.canada.ca/species-risk-registry/virtual_sara/files/cosewic/sr_Westslope%20Cutthroat%20Trout_2016_e.pdf) so WCT rearing habitat should include lakes/reservoirs/wetlands.  Looks like wetlands are currently included but maybe not lakes/reservoirs? 

Found this but wondering where the `wct_lakereservoir_ha `might tally in?
https://github.com/smnorris/bcfishpass/blob/ab8f9f5d6c228b7c257eec6353bc84b1d20b8ec4/scripts/model/sql/point_report.sql#L663

Here is an example of how `wct_lakereservoir_ha `does not show up for modelled crossing 4606370 (PSCIS 197787) when there is total_lakereservoir_ha = 2.06 with potential habitat upstream (WCT were observed in this lake in July 2021).  Was the wct_lakereservoir_ha meant to show up?

![image](https://user-images.githubusercontent.com/46538103/156778475-688ce7dd-981f-4b86-a9b6-220ebbd0e2f1.png)

![image](https://user-images.githubusercontent.com/46538103/156780968-2437c82e-75ac-428d-8165-ba0c83b3045d.png)

**Comment by smnorris** [comment]
This is a bug. 
Looks like it has been there a while too, results in that column will be off anywhere that there is not also a reservoir upstream.

**Comment by smnorris** [comment]
This does not address WCT rearing model, I'll open another issue for that
