### ISSUE TITLE
watershed_upstr_ha not calculating in crossings table (zero values). No map_upstream or watershed_upstr_ha in streams table

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#194]
Where can we access these attributes now?  

ex.
```
SELECT aggregated_crossings_id, watershed_upstr_ha
   FROM bcfishpass.crossings_20220228
   WHERE watershed_group_code IN ('ELKR')
```

**Comment by smnorris** [comment]
Thanks for the review! I think these were oversights while cleaning things up.

- `watershed_upstr_ha` is now `upstream_area_ha`, I will add it back to the crossings table, not sure why it is currently commented out - areas are held in the `whse_basemapping.fwa_watersheds_upstream_area` table
- `map_upstream` is in `bcfishpass.mean_annual_precip`, and I can add that back to the crossings table too

**Comment by smnorris** [comment]
I think we can add these columns when creating the crossings table (in `crossings.sql`) rather than when running habitat summaries (`point_report.sql`).

This makes generating the crossings table dependent on the channel width scripts, but that is fine.

**Comment by smnorris** [comment]
`map_upstream`, `upstream_area_ha` added to `bcfishpass.streams`
