### ISSUE TITLE
Iterative scripting of species specific modelling and associated output column names

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#197]
Obviously, if there is a way to loop over the different species from the [user supplied spreadsheets](https://github.com/smnorris/bcfishpass/tree/main/parameters) so that only one set of scripts runs all the models for all the species and names the output columns accordingly the flexibility would increase and the complexity of the addition of new species would potentially decrease. Filing this issue might be a bit like pointing out that we should try for world peace.

**Comment by smnorris** [comment]
Yes, this has been on my mind - and now that the scripts are better organized I think this is possible and probably not too difficult. A couple of goals:
- allow quick, per species model runs
- don't require user to tweak the `Makefile`

I'm still learning my way around `make` but my goal with the current version was maintaining a provincial crossings layer fairly easy - updates to the lookups/fix tables are found and processed automatically and summaries can be re-run without re-processing the natural barriers and habitat models. 

One data model change that might make per-species modelling easier is to create per-species output tables rather than adding all the columns to `streams` and `crossings` every time. 

Anyway, world world peace would be better but I think we can probably get this done once other priorities are dealt with.

**Comment by smnorris** [comment]
I wonder just how many more species might be added to the list? 

Reworking the scripts to accept new species and models from the parameters would be very valuable - there are currently too many spots where sql has to be edited/added to add new species.

But if the primary iterations are on gradient and discharge/CW thresholds as already provided in the parameters, maybe this refactoring isn't really worth the effort at this point, or at least is not high priority?  

At the moment, new habitat models likely required are:
- PK
- CM
- GR
- RB
- KO

**Comment by smnorris** [comment]
With simplification happening in branch `per_wsg`, it should be relatively simple to modify things to process only species listed in parameters file. I'd probably ditch the makefiles in `model_access` and `model_habitat` and replace with very simple python scripts. Things then also get easier to maintain!

Potentially, but more challenging, the Python scripts could handle additional habitat parameters and inject them into queries like https://github.com/smnorris/bcfishpass/blob/per_wsg/scripts/model_habitat/sql/model_habitat_ch.sql.  This could be quite tricky though, given how variable habitat queries can be for different species.

Finally, tweaking output column names is much more challenging - one of bcfishpass' key scripts is https://github.com/smnorris/bcfishpass/blob/per_wsg/scripts/model_access/sql/functions/break_streams.sql - and the query currently has to hard code all columns present in the streams table in order for it to work quickly. Despite this annoyance, it is working really well, I would prefer not to touch it (other than adding any new columns for new species). I'm sure dynamically generating this query with per-species column names is possible but doesn't seem worth the time investment.

**Comment by smnorris** [comment]
I think tweaking https://github.com/smnorris/bcfishpass/blob/per_wsg/scripts/model_access/sql/functions/break_streams.sql to automatically generate the list of columns is probably higher priority than trying to generate dynamic queries for per-species habitat parameters and models.  

If `break_streams` and any similar functions just go ahead and handle whatever columns are present, the steps for adding a species or scenario would be to:
- edit the parameters files, listing what groups to process and what the habitat parameters may be
- edit `wsg_species_presence.csv` to note where the species occurs
- add `scripts/model_access/model_access_<spp>.sql file, defining barriers for the given spp
- add `scripts/model_habitat/model_habitat_<spp>.sql, defining how the habitat works
bcfishpass could pick up these files and run the spp scenario accordingly

I'll at least identify and document the steps for adding species currently - and try to make the list of steps shorter and simpler as updates happen.

**Comment by NewGraphEnvironment** [comment]
Just to monkey wrench everything, I want to mention that I have a hard time seeing a future where we will not add parameters like "distance to core habitats", "alvin emergence to winter - accumulated thermal units", "alkalinity" and "riparian structure" to help us place a weighted "value" on habitats. Maybe all this madness doesn't fit in the `bcfishpass` universe now or eve4r but wanted to throw it out there because these variables influence fish productivity right alongside gradient and stream discharge...

**Comment by NewGraphEnvironment** [comment]
Totally. And we continue to work with @joethorley and @evanamiesgalonski on eventually deriving the inputs to the scaled weightings using Bayesian modelling!

**Comment by smnorris** [comment]
Closing in favour of https://github.com/smnorris/bcfishpass/issues/281

With modification of the two files noted in that issue, access models can be created by dropping in a new `model_access_<spp>.sql` that defines your species/gradients of interest. Generating these queries via a parameters file does not seem worth the effort - there are too many quirks in each model, it isn't as simple as just setting a gradient threshold.
