### ISSUE TITLE
pull dams (and falls?) from CABD

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#222]
Extract features from CABD with this request:
`https://cabd-web.azurewebsites.net/cabd-api/features/dams?filter=province_territory_code:eq:bc`

Barrier status is in `passability_status_code`
https://github.com/smnorris/bcdams/issues/6#issuecomment-1081081342

**Comment by nickw-CWF** [comment]
Replying here because ``bcdams`` was archived.

We've been focusing on compiling and process data up to this point, so we haven't put too much thought into how to handle updates. In the long term, we want to set up a proper data entry portal, but in the short term I think we can set up some scripts to ingest csv's similar the the ``bcfishpass`` fix tables. I'll talk to Alex and Katherine about setting up a csv template for that.

**Comment by nickw-CWF** [comment]
FYI, we have a development version of our CABD documentation site up for testing. It can be found here: https://cabd-docs.netlify.app/. It is incomplete and the populated content is in first draft form, but the API section is relatively complete for additional reference.

Also, credit to you for bringing Sphinx to my attention for documentation. It's a great framework!

**Comment by smnorris** [comment]
Nice! Thanks Nick.

Given the timelines I'll probably stick with `bcdams` for the current railway reporting but hopefully a near future bcfishpass data and code release can use CABD.

**Comment by nickw-CWF** [comment]
> Falls could/should also come from CABD?

Yes, I think this is best long-term. No need to maintain two separate falls datasets. ID issues may not be relevant for falls since they don't get assigned an ``aggregated_crossings_id``?

**Comment by smnorris** [comment]
Correct, 'natural' barriers don't get a crossing id.

Note that I have a data extract of FISS falls that a user noticed as absent from the published dataset way back in 2014.  Unfortunately the data remains unpublished, so I expect there may be a few features in it that are not yet in CABD:

https://github.com/smnorris/bcfishpass/blob/main/scripts/falls/falls.sh#L32
https://hillcrestgeo.ca/outgoing/public/whse_fish/whse_fish.fiss_obstacles_unpublished.csv.zip

**Comment by TomasMillaKoch** [comment]
For pulling the CABD into postgres, I am currently using the two scripts from the bcdata repo that @smnorris sent along. In order to populate a postgres table to replace bc_dams, I am writing an independent script that calls the CABD api. Before I continue, is this an acceptable way of proceeding? Is this the structure that was envisioned for this task?

**Comment by nickw-CWF** [comment]
> Correct, 'natural' barriers don't get a crossing id.
> 
> Note that I have a data extract of FISS falls that a user noticed as absent from the published dataset way back in 2014. Unfortunately the data remains unpublished, so I expect there may be a few features in it that are not yet in CABD:
> 
> https://github.com/smnorris/bcfishpass/blob/main/scripts/falls/falls.sh#L32 https://hillcrestgeo.ca/outgoing/public/whse_fish/whse_fish.fiss_obstacles_unpublished.csv.zip

Interesting, is the unpublished data open, i.e., can we pull it and work on incorporating it into the CABD?

**Comment by smnorris** [comment]
>For pulling the CABD into postgres, I am currently using the two scripts from the bcdata repo that @smnorris sent along. In order to populate a postgres table to replace bc_dams, I am writing an independent script that calls the CABD api. Before I continue, is this an acceptable way of proceeding? Is this the structure that was envisioned for this task?

Fine by me.  Using geopandas makes the data transfer very simple.
```
df = geopandas.read_file(url)
df.to_postgis(table, db)
```

If you want to try out using a postgres foreign data wrapper, that works too. It would be neat to ensure the db is always in sync with CABD. But since everything else depends on loading various datasets via separate scripts anyway, I wouldn't bother putting much effort into this approach.

**Comment by smnorris** [comment]
> https://hillcrestgeo.ca/outgoing/public/whse_fish/whse_fish.fiss_obstacles_unpublished.csv.zip
> 
> Interesting, is the unpublished data open, i.e., can we pull it and work on incorporating it into the CABD?

Presumably, but it was never explicit - might be worth asking @CaptainMarmot. The provincial FISS contact I got the data from has since retired.

**Comment by smnorris** [comment]
with https://github.com/smnorris/bcfishpass/commit/4e27027c021e7c445d5718edde84965b166ba12b, dams are now sourced from CABD
