### ISSUE TITLE
add `WHSE_FOREST_TENURE.FTEN_RANGE_POLY_SVW` to mapping

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#228]
[WHSE_FOREST_TENURE.FTEN_RANGE_POLY_SVW](https://catalogue.data.gov.bc.ca/dataset/range-tenure/resource/e1cfe292-8ee1-4f67-9032-941198df8c6f)  

Key for recognizing cattle related riparian issues on crown lands. Nice to know for access too

**Comment by smnorris** [comment]
modify the default symbology so that the range polygons do not overwhelm the map. Consider an outline symbol (rather than shading the entire poly) for these and maybe also for watersheds upstream of confirmations.

**Comment by smnorris** [comment]
Fixed by planarizing the tenures.
