### ISSUE TITLE
Makefile bails at line 315

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#231]
1. Is there a way to bypass the makefile and run `scripts/model` manually? 
2. Also not sure how to try to get the functions into postgres. All other scripts have been run individually besides `lateral` and `misc`

`CREATE TABLE
psql postgresql://postgres@localhost:5432/bcfishpass -v ON_ERROR_STOP=1           -c "DELETE FROM bcfishpass. param_watersheds"
DELETE 9
psql postgresql://postgres@localhost:5432/bcfishpass -v ON_ERROR_STOP=1           -c "\copy bcfishpass. param_watersheds FROM 'parameters/watersheds.csv' delimiter ',' csv header"
COPY 9
touch .param_watersheds
echo "SELECT bcfishpass.create_barrier_table(:'barriertype')" | psql postgresql://postgres@localhost:5432/bcfishpass -v ON_ERROR_STOP=1           -v barriertype=falls
ERROR:  function bcfishpass.create_barrier_table(unknown) does not exist
LINE 1: SELECT bcfishpass.create_barrier_table('falls')
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
make: *** [Makefile:315: .barriers_falls] Error 3`

**Comment by NewGraphEnvironment** [comment]
For 2 - build .sh file to load functions

**Comment by NewGraphEnvironment** [comment]
built .sh file to load 'load_tables'

**Comment by smnorris** [comment]
- .functions target needs to be referenced by .db or something else that comes before the barrier_load is called
- some tables in model/sql/tables are outdated ( remove definitebarriers<>) and some may be missing from makefile

**Comment by NewGraphEnvironment** [comment]
I have a new database with a fresh dump of all schemas for `fwapg` and `bcfishobs` outputs and have cloned a fresh branch of this [fork](https://github.com/NewGraphEnvironment/bcfishpass/tree/202301_remote).  Local version of fork has `watersheds.csv` (one test watershed group) and the `habitat.csv` files in the `parameters` directory.  Can't seem to get any action and forget how we might hack it to get it to run.  Any ideas?

![image](https://user-images.githubusercontent.com/46538103/214904697-114f5d42-b897-4049-826b-11b9bcabf3bc.png)

**Comment by smnorris** [comment]
Closing this as the makefile has changed and target is to get it completely functional / tested on new db
