### ISSUE TITLE
script in layers needed for qgis

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#232]
they look like this

![Screen Shot 2022-05-13 at 3 19 09 PM (4)](https://user-images.githubusercontent.com/46538103/168396454-1f85e9d8-2fa0-4348-aafc-0764542a0d74.png)

**Comment by NewGraphEnvironment** [comment]
`cd qgis`
`make`

ha

**Comment by NewGraphEnvironment** [comment]
solution is to 

`mkdir .make` first before running `make`

maybe best to just add this to the readme?

leaving open for now

**Comment by smnorris** [comment]
Leave it open, the male file should create that folder
