### ISSUE TITLE
use 'DROP TABLE <>, CREATE TABLE <>` pattern when setting up db rather than CREATE TABLE IF NOT EXISTS

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#233]
reference for future PR. 

`scripts/discharge/Makefile`

**Comment by smnorris** [comment]
The sequence for this and all similar scripts should be probably be like this:
```
DROP TABLE IF EXISTS <>;
CREATE TABLE <> ;
```

This ensures the table being created is fresh - `create table if not exists` can result in hard to track down errors if the table schema has changed elsewhere in the code.
