### ISSUE TITLE
Makefile errors for setting up .functions and building tables in model/sql/tables

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#234]
place to link to commit that was the work around in case it sheds light.  might have been user error as usual though....

**Comment by smnorris** [comment]
`.functions` is required by `.crossings` but maybe that should be moved up to an earlier target.

**Comment by smnorris** [comment]
You've called all queries in `model/sql/tables` - it does look like some might be missing from the makefile. And also some are no longer used and should be removed : `definitebarriers_<spp>`

**Comment by smnorris** [comment]
#231 better describes the issue
