### ISSUE TITLE
Details for cdo and netcdf install on M1mac

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#236]
place to reference potential readme tweaks to help M1 users get up and running AFAP

**Comment by smnorris** [comment]
Using `brew` seems ideal until `conda-forge` has ARM builds. Not sure why I didn't do this.
I'll hold off for a little bit as it does seem like there is some activity with ARM support
https://github.com/conda-forge/cdo-feedstock/pull/110

**Comment by smnorris** [comment]
added this to the main README
