### ISSUE TITLE
remove dnstr_crossings when crossing type = OBS and barrier_status = PASSABLE

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#24]
When modelled crossings meet modelled habitat-based criteria that flags them as potentially important and `dnstr_crossings is NULL` it allows the reviewer to have a look at only the most downstream crossing within the watershed of interest. If that crossing looks like a good crossing to follow up on in the field it can be assumed that the rest of the crossings upstream will be looked at in turn if/when it makes sense.

Currently, all modelled_crossings that meet my [habitat-based query](https://github.com/NewGraphEnvironment/fish_passage_elk_2020_reporting_cwf/blob/master/R/extract-bcfishpass-planning.R) in the Upper Elk River have dnstr_crossings .  A review of a subset of these indicates that often these crossings are actually on the Elk River and have a `barrier_status` of `PASSABLE` (ex `aggregated_crossings_id` = `22095` and `aggregated_crossings_id` = `9510`) .

Is there a way to pull the `aggregated_crossings_id `with the `barrier_status` = `PASSABLE` out of the `dnstr_crossings` column of the `crossings` layer or add another queriable column for review purposes?

**Comment by smnorris** [comment]
Would using `bcfishpass.barriers_anthropogenic` fix this? This pulls records from `bcfishpass.crossings`, but only those that are barriers/potential barriers. 

Don't use `aggregated_crossings_id` for reference, that is currently unstable - the values in the `ali.crossings` schema don't match those in `bcfishpass.crossings`. Use `modelled_crossing_id`/`stream_crossing_id`/`dam_id` - I should be able to remove the `aggregated_crossings_id` column completely, see https://github.com/smnorris/bcfishpass/issues/18

**Comment by NewGraphEnvironment** [comment]
Yes.  This works.  I was able to recreate and join to previous review work joining on `modelled_crossing_id`/`stream_crossing_id`/`dam_id`.  Thank you!

**Comment by NewGraphEnvironment** [comment]
hmm. but now I don't see a bunch of modelled_crossings that might be good candidates to look at in the field.  I will need to try to get the `dnstr_barriers_anthropogenic` column joined into the `crossings` table.  I'll give it a try

**Comment by smnorris** [comment]
If they haven't been assessed they should show up in the barriers table. 

Looking back, I forgot that I actually already include `dnstr_barriers_anthropogenic` in the `crossings` table - you shouldn't have to join?

Joining on the various `[integer]` columns that list upstream/downstream ids should work ok but I haven't indexed them or tested it out. Should work fairly well once indexed: https://www.postgresql.org/docs/12/intarray.html

**Comment by smnorris** [comment]
With #18 fixed, `dnstr_barriers_anthropogenic` values are now stable - use the latest data if joining based on these values and where values are > 1B, subtract 1B from the id value before joining.

**Comment by smnorris** [comment]
I'm going to close for now - but please re-open if there are remaining issues.
