### ISSUE TITLE
gdalwarp issue

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#241]
from @NewGraphEnvironment 

> Not sure why `gdalwarp` thinks `-te minx>=maxx`. Any idea?
> 
> ```
> download: s3://esa-worldcover/v100/2020/map/ESA_WorldCover_10m_2020_v100_N48W126_Map.tif to ../../../../../../../tmp/ESA_WorldCover_10m_2020_v100_N48W126_Map.tif
> gdalbuildvrt /tmp/esa_merged.vrt /tmp/ESA_WorldCover_10m_2020_v100_*.tif
> 0...10...20...30...40...50...60...70...80...90...100 - done.
> gdalwarp -co COMPRESS=DEFLATE \
>         -co PREDICTOR=2 \
>         -co NUM_THREADS=ALL_CPUS \
>         -t_srs EPSG:3005 \
>         -r nearest \
>         -te "728087.5, 446687.5, 1542387.5, 1263287.5" \
>         -tr 25 25 \
>         /tmp/esa_merged.vrt \
>         data/esa_bc.tif
> Warning 1: -te values have minx >= maxx. This will result in a horizontally flipped image.
> Copying color table from /tmp/esa_merged.vrt to new file.
> Creating output file that is -117791P x 4L.
> ERROR 1: Attempt to create -117791x4 dataset is illegal,sizes must be larger than zero.
> make: *** [Makefile:59: data/esa_bc.tif] Error 1
> ```
> 
> `[-te xmin ymin xmax ymax]`
> looks fine to me.. Makes no sense... 
> ![Rplot](https://user-images.githubusercontent.com/46538103/168871082-e893074a-2fd8-4ed8-98a5-50f604e4cb06.png)
> 
> _Originally posted by @NewGraphEnvironment in https://github.com/smnorris/bcfishpass/issues/191#issuecomment-1128402778_

**Comment by smnorris** [comment]
@NewGraphEnvironment I'm closing - I think you got this to run without issue this year?

**Comment by NewGraphEnvironment** [comment]
ran like a dream recently. thanks Simon
