### ISSUE TITLE
reporting - add pgfs compatible functions for common reports

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#245]
- choose location for scripts to live
- add target to makefile that calls the scripts/loads the functions

See https://github.com/smnorris/fwapg/tree/main/sql/functions for reference.
Use latest pgfs (may require compiling the go code) when testing to ensure CRS handling is correct

**Comment by nickw-CWF** [comment]
Does [bcfishpass/main/wcrp](https://github.com/smnorris/bcfishpass/tree/main/wcrp) work for the location?

**Comment by smnorris** [comment]
Yes, that is perfect

**Comment by smnorris** [comment]
I think I might actually put them in /reports/wcrp

Everything in /wcrp can probably be shuffled around to other subfolders or removed.

**Comment by smnorris** [comment]
@nickw-CWF @TomasMillaKoch - do we want to expose these functions to all users of the db, or just to pg_featureserv?

**Comment by smnorris** [comment]
WCRP functions are published here: https://features.hillcrestgeo.ca/bcfishpass/functions.html

Give them a test and let me know if there are any issues.

**Comment by smnorris** [comment]
For consistency, the function arguments should probably `watershed_group_code` rather than `watershed_group`

**Comment by nickw-CWF** [comment]
> @nickw-CWF @TomasMillaKoch - do we want to expose these functions to all users of the db, or just to pg_featureserv?

I don't see any reason to not expose them to all db users.



> WCRP functions are published here: https://features.hillcrestgeo.ca/bcfishpass/functions.html
> 
> Give them a test and let me know if there are any issues.

When I open up the link, the Functions page is blank. @TomasMillaKoch is this the same for you?



> For consistency, I think the function watershed parameter and response should be `watershed_group_code` rather than `watershed_group` and `watershed` respectively.

When @TomasMillaKoch was testing the functions they were throwing errors with ``watershed_group_code`` as an input parameter because of duplicate variables of the same name in the query. But maybe this is a solvable issue?

**Comment by smnorris** [comment]
Fixed - sorry. The permissions have to be updated any time the functions are tweaked.
I think they work fine now. I was using `watershed_group_code` and wondering why I wasn't getting any responses.
This is probably solvable - I had to tweak the first function with a similar issue.

**Comment by smnorris** [comment]
> I don't see any reason to not expose them to all db users.

Agreed. I would have done this but it is a bit more work to manage and the code likely gets duplicated. Functions for pgfs must reside in schema `postgisftw`. For a function to not be listed on all pgfs services using the db, permissions have to be explicitly granted/revoked on individual functions.  A workaround to avoid having to manage these grants is to duplicate the functions in `bcfishpass`.  This also makes more sense to me from a discovery/user standpoint. 

I'll take a closer look when next running a replication of the model to the production dbs.

**Comment by smnorris** [comment]
I've updated the functions to use parameter `watershed_group_code`. 
Looks like the output column name cannot easily be equivalent but within the queries the conflict can be avoided by qualifying the column names with the table alias.

sample query:
https://features.hillcrestgeo.ca/bcfishpass/functions/postgisftw.wcrp_barrier_count/items.json?watershed_group_code=ELKR

**Comment by smnorris** [comment]
All functions are testing successfully for me except for this:
https://features.hillcrestgeo.ca/bcfishpass/functions/postgisftw.wcrp_watershed_connectivity_status/items.json?watershed_group_code=ELKR

We are missing `WCT` habitat in the connectivity status query. Can you add this @TomasMillaKoch ?

**Comment by TomasMillaKoch** [comment]
Yes I will send you an updated query.

**Comment by nickw-CWF** [comment]
> All functions are testing successfully for me except for this: https://features.hillcrestgeo.ca/bcfishpass/functions/postgisftw.wcrp_watershed_connectivity_status/items.json?watershed_group_code=ELKR
> 
> We are missing `WCT` habitat in the connectivity status query. Can you add this @TomasMillaKoch ?

@smnorris I realized that because of how we handled ``ELKR`` for the WCRP (splitting it into separate "units" above Elko dam and below) we will likely need a custom function to generate the connectivity status for each units. Theoretically we wouldn't need to incorporate ``WCT`` into ``wcrp_watershed_connectivity_status`` at this time, but I supposed in the future we might want to report on WCT watersheds as a whole in other parts of the province. Do you think other users would be interested in that?

**Comment by smnorris** [comment]
It seems valuable to me but maybe not a short term priority. @NewGraphEnvironment may have thoughts re the utility for other users.
