### ISSUE TITLE
crossing ids

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#255]
Related to #222 - maintaining the unique, range-defined `aggregated_crossings_id` in the `crossings` table is awkward, and becomes more difficult when we bring in features with UUIDs from CABD (dams). 

Options:

1. Keep aggregated_crossings_id but support text based ids as input
It appears we are not actually using the intarray extension on the crossing ids - arbitrary types within the upstream/downstream arrays may be fine.

2. Use serial integers autocreated on creation of `bcfishpass.crossings` 
This would make things super simple but the ids would change on every model run. Fine if they are only used internally.

3. Use unique integers based on network position
Combining blue_line_key and downstream_route_measure (to nearest mm) as per [segmented_stream_id](https://github.com/smnorris/bcfishpass/blob/main/scripts/model/sql/tables/streams.sql#L11), but as an integer

For options 2 and 3, applications can include logic to label a crossing with the source id - ie PSCIS `stream_crossing_id`, bcfishpass `modelled_crossing_id`, CABD `cabd_id` etc.   Usage of the database is more cumbersome because the indexed ids (ie, list of crossings upstream or downstream) will no longer correspond to source id values, they would have to be cross referenced - ie it would no longer be possible to tell exactly which PSCIS barriers are downstream of a given crossing with a quick scan of `barriers_anthropogenic_dnstr`

**Comment by smnorris** [comment]
https://github.com/smnorris/bcfishpass/commit/8ac22d59c7e48c9a06700437de804f447f3be7bd changes `aggregated_crossings_id` to `text` type as per option 1.

**Comment by nickw-CWF** [comment]
> [8ac22d5](https://github.com/smnorris/bcfishpass/commit/8ac22d59c7e48c9a06700437de804f447f3be7bd) changes `aggregated_crossings_id` to `text` type as per option 1.

I agree that this is best solution at this point - keeps things nice and easy for stream crossings, while also allowing for the CABD ids and keeping everything stable. If there are hiccups in the future and you want to re-evaluate, let me know.

**Comment by smnorris** [comment]
There are a few more changes required to support the text based ids - I'm working through a test model run to find the issues.
It should work but I am not yet certain.

**Comment by smnorris** [comment]
For reference, here is the code for option 3 - unique id generation using blkey and measure :
https://github.com/smnorris/bcfishpass/blob/main/scripts/model/sql/barriers_gradient_05.sql#L16

`(((b.blue_line_key::bigint + 1) - 354087611) * 10000000) + round(b.downstream_route_measure::bigint) as barrier_load_id`

**Comment by smnorris** [comment]
Everything seems to be working with option 1. 

Any references to the Elko dam in various WCRP queries need to be updated with the new id, hopefully that is the last change.
