### ISSUE TITLE
crossings table - add MOT culvert id

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#268]
Find closest MOT culvert within n metres and add the MoT ID. 
https://catalogue.data.gov.bc.ca/dataset/ministry-of-transportation-mot-culverts/resource/73e5e4f9-5f83-4ace-ad0b-14f6d2710bdd

This is mainly for ownership purposes. If a crossing is potentially matched to an MoT culvert the user can look up more info in the MoT dataset, these columns could be valuable:
```
CULVERT_TYPE
CULVERT_DIAMETER
CULVERT_MATERIAL
INSTALLATION_DATE
FISH_SENSITIVE_CODE
FISH_PASSAGE_TYPE
GRATE_CODE
FLAP_GRATE_CODE
```
At the moment I don't see a need to pull this data into the crossings table for modelling passability:
- diameter data seems a bit inconsistent and MoT points are per-pipe, there are many more culvert points than bcfishpass crossings in a given area - matching the mot culvert to the correct stream/bcfishpass crossing may be challenging
- fish_sensitive_code is empty
- fish_passage_type sounds most promising but very few culverts have this information (non/other/unknown/null all seem to be equivalent, and the baffles are primarily along a single stretch of highway)
```
 count  | fish_passage_type
--------+-------------------
    194 | Baffle
      2 | Bottomless
      8 | Fish Ladder
   1828 | None
   3478 | Other
 166272 | Unknown
  14748 |
```

**Comment by NewGraphEnvironment** [comment]
linking `CHRIS_CULVERT_ID` to the `modelled_crossing_id` seems like it will have massive benefits for the folks at MoTi and their consultants

**Comment by smnorris** [comment]
Feedback from MoTI consultants agrees - too many MoTI culverts makes it challenging to do an automated matching. Since they are are building their own culvert risk system we don't really need to add this ID to our database (at this point).  We can let the MoTI consultants do the join and just use the culverts for background in the field.
