### ISSUE TITLE
access model - historic habitat

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#271]
With addition of columns `barriers_dams_dnstr` and `barriers_dams_hydro_dnstr` to the streams table it is easy to visualize/report on stream isolated specifically by dams. However, it is not always appropriate to presume that all potential habitat upstream of a dam was historically accessible - dams are generally built at locations where there may have been a natural barrier.  This will have to be reviewed case by case but is not likely to be a big job if just reviewing hydro dams.

**Comment by NewGraphEnvironment** [comment]
guessing there is no way to add Kootenai Falls (https://en.wikipedia.org/wiki/Kootenai_Falls) to user_barriers_definite.csv because it is in the states? 

Would we add [Bonnington Falls ](https://en.wikipedia.org/wiki/Bonnington_Falls)though and then the model would consider upstream areas like Kookanusa Reservoir (upstream of Kootenai_Falls) non-historic?

**Comment by smnorris** [comment]
As a temporary measure, Kootenai could be added at the border. Probably on the Kookanusa flow line, but I can check.

Yes, adding Bonnington should would work as you describe.

**Comment by smnorris** [comment]
https://github.com/smnorris/bcfishpass/commit/dfd371120affce9ccdaadc9f791391ef3fc8165d

**Comment by NewGraphEnvironment** [comment]
Awesome!

https://columbiariversalmon.ca/wp-content/uploads/MAP-CRSRI-1.pdf

https://columbiariversalmon.ca/about/the-salmon/

**Comment by smnorris** [comment]
I have a large habitat dataset almost ready to load (known spawning locations from PSF) - once it is good to go I'll update the model with this change as well.

**Comment by smnorris** [comment]
No real resolution to this, but closing for now as it is basically a data issue that needs to be resolved per-barrier.
