### ISSUE TITLE
`make .make/model_access` simply touches new file in `.make` directory

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#289]
This is from scratch with only `fwapg` and `bcfishobs` outputs in the database.

```
$ make
make: *** No rule to make target 'model/habitat_lateral/data/habitat_lateral.tif', needed by 'all'.  Stop.
```

```
$ make .make/crossing_stats
touch .make/model_access
touch: cannot touch '.make/model_access': No such file or directory
make: *** [Makefile:131: .make/model_access] Error 1
```

```
make .make/setup
RUNS!
```

```
$ make .make/data
RUNS but only generates the '.make/data' target
````

```
$ make .make/crossing_stats
make: *** No rule to make target '.make/precipitation', needed by 'model/channel_width/.make/channel_width'.  Stop.
```
```
$ make .make/model_access
touch .make/model_access
```

```
$ make .make/model_access
make: '.make/model_access' is up to date.
```

But model_access didn't actually run...  See screenshot of the targets created below.

![image](https://user-images.githubusercontent.com/46538103/218616549-f3bd605f-a5d4-4708-bd1f-0c11d8bd7ba0.png)

**Comment by smnorris** [comment]
- lateral habitat target is incorrect
- looks like my attempt to create a target that will build both access model and run the QA scripts didn't work
 
Try this if you want to get started:
```
make clean
make model/access/.make/model_access
```

**Comment by NewGraphEnvironment** [comment]
hiccups. 

Had an interesting error earlier on the sql/observations.sql script where it was looking for something from `bcfishobs.fiss_fish_obsrvtn_events_vw` .  It said it wasn't there and failed out so I rebuilt `bcfishobs`.  The funny thing is that I don't see that table still after the rebuild but it did generate that target so I assume it was all good.  Odd stuff because that is the name of the table in the [`readme`](https://github.com/smnorris/bcfishobs). Coincidence?
```
newgraph-# \dt bcfishobs.*
                       List of relations
  Schema   |              Name              | Type  |  Owner
-----------+--------------------------------+-------+----------
 bcfishobs | fiss_fish_obsrvtn_events       | table | postgres
 bcfishobs | fiss_fish_obsrvtn_events_sp    | table | postgres
 bcfishobs | fiss_fish_obsrvtn_pnt_distinct | table | postgres
 bcfishobs | fiss_fish_obsrvtn_unmatched    | table | postgres
(4 rows)
```




Anyway got it chugging and now but it is telling me I don't have the `stream_order_parent ` column in the streams table while pg tells me I do.... I will run make again and see if it actually sees it this time but sure seems oddball.

```
+ psql postgresql://postgres@localhost:5432/newgraph -v ON_ERROR_STOP=1 -f sql/streams.sql
DROP TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ parallel psql postgresql://postgres@localhost:5432/newgraph -v ON_ERROR_STOP=1 -f sql/streams_load.sql -v 'wsg={1}' ::: ATNA BABL BABR BELA BLAR BULK CARP CHIL CRKD ELKR EUCH EUCL HOMA KISP KITL KLIN KOTL LCHL LCHR LDEN LEUT LNRS MORR NAZR NECL NECR PARS UCHR UDEN UEUT ZYMO
psql:sql/streams_load.sql:52: ERROR:  column s.stream_order_parent does not exist
LINE 32:   s.stream_order_parent,
```

```
newgraph=# select column_name
from information_schema.columns
where table_name = 'streams';
       column_name
--------------------------
 segmented_stream_id
 linear_feature_id
 edge_type
 blue_line_key
 watershed_key
 watershed_group_code
 downstream_route_measure
 length_metre
 waterbody_key
 wscode_ltree
 localcode_ltree
 gnis_name
 stream_order
 stream_magnitude
 gradient
 feature_code
 upstream_route_measure
 upstream_area_ha
 stream_order_parent
 stream_order_max
 geom
(21 rows)
```

**Comment by smnorris** [comment]
`bcfishobs.fiss_fish_obsrvtn_events_vw` is a view, try:

`newgraph-# \dv bcfishobs.*`

**Comment by NewGraphEnvironment** [comment]
ah lovely. Same error with the `model_access` build so going to try rebuilding `fwapg` with the latest commits on board and putting it down for the day

**Comment by smnorris** [comment]
👍  the latest fwapg adds that column to the main streams table.
