### ISSUE TITLE
python version specified in `environment.yml` and `cdo` from `conda` for linux virtual environment

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#293]
looks like, currently, the virtual environment won't build on linux due to some sort of incompatibility with the latest python version (3.11).  Seems to build fine with a call to `- python=3.10` in the `environment.yml`

Additionally, is it worth considering two `.yml` files so that `cdo` can be rolled into the env build for linux machines and not need to be installed from source? Seems like the `cdo` install might be quite the gymnastics routine on linux and it can be easily avoided by including it in the virt env...

**Comment by smnorris** [comment]
I haven't tried building on Linux yet. Pinning to Python 10 is fine. If you get a successful build with another environment.yml create a PR - I won't get to building on Linux for a week or two at least.

Tempting to build a docker image, but I'm not sure it is worth the time investment

**Comment by smnorris** [comment]
I actually don't bother with conda on linux, there is no real need. 
We don't seem to require bleeding edge releases of the various tools anymore, just installing via the package manager is fine.

But I haven't tried running `cdo` or any of the CW/MAD modelling on that platform, or the lateral habitat.

Building a docker image would probably not be that difficult, this one needs to be updated but covers most of the requirements:
https://github.com/smnorris/fwapg/blob/main/Dockerfile

**Comment by smnorris** [comment]
I'm going to close this for now. 
Model processing is now scheduled via GHA/linux where a conda environment is not required (all python dependencies can be pip installed). We do not currently require `cdo` because pre-processed discharge etc are available and do not need to be refreshed (and this job should be moved to a separate repository anyway).
