### ISSUE TITLE
BT discharge thresholds

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#334]
No discharge thresholds are currently provided for BT spawning/rearing in the parameters.
@NewGraphEnvironment - is this an issue? Just use CW everywhere for BT for now? 

I'm surprised this issue hasn't already popped up, I am not sure what BT spawning/rearing would currently look like in Fraser watersheds where discharge is used, with the null parameters I'd guess it would be empty.

confirmed - no modelling of BT in Fraser/Peace in current output. 
Options:
- modify param to use CW everywhere
- add discharge param for BT
- modify BT model to use CW only

**Comment by NewGraphEnvironment** [comment]
Let's modify param to use CW everywhere for now until we can understand both the accuracy of MAD estimates in streams small enough for culverts as well as why certain thresholds are being applied to specific species. 

My understanding is that our ability to use real data for channel width as well as calibrate estimates on small streams with real data far far exceeds that for deriving MAD.
