### ISSUE TITLE
PSCIS data flow

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#373]
If we want a stable database and reports, new PSCIS crossings should not be included in the bcfishpass db without first being reviewed by a human - crossings on unmapped tribs are incorrectly snapped to nearby rivers.

For example, stream_crossing_id 198347 (assessed March 22, 2023) was automatically loaded and matched to the Eve River, incorrectly blocking 82km of potentially accessible Steelhead "habitat" upstream. More can probably be done to improve the accuracy of matching crossings to streams - but it is unlikely to ever be perfect.

Review of the handful of crossings that make it in to the system should be quick and easy but:
- who might do this review? 
- on what schedule?

@captainmarmot @NewGraphEnvironment

**Comment by CaptainMarmot** [comment]
Thanks for mentioning this Simon - good catch.
I think anything we can do to automate this check would be a good thing.  The original PSCIS load routine has a spatial check which confirms the co-ordinates are inside BC but this is more involved for sure.  
The hope is to eventually move away from ESF submissions and have the Survey 123 generated submission go straight into the Oracle data tables.  I can discuss this idea with the GeoBC folks who are working on that and see if there is a point in the validation process where we could try to do this.

**Comment by CaptainMarmot** [comment]
How do I add another person to this issue?  I was going to loop Eric Milan from GeoBC in.

**Comment by smnorris** [comment]
All my thoughts above were related only to bcfishpass though - adding checks to PSCIS itself might be a better fix but that is a much different question.

**Comment by CaptainMarmot** [comment]
Understood - thanks for clarifying that.  So I guess that would be a check / correction that would have to happen on your end?

**Comment by smnorris** [comment]
Yes, once the points are matched to streams, there could be a filter on the max length upstream for barriers. 

https://github.com/smnorris/bcfishpass/blob/main/model/01_access/pscis/sql/04_pscis.sql

We would have to determine

- what would be the threshold
- would a crossing be filtered out or just flagged for review
- who/when would review the filtered crossings and match them to correct stream (where possible)

**Comment by smnorris** [comment]
Another PSCIS data fix that I'm not sure how to apply in bcfishpass - office review indicates a bridge at pscis crossing id 196200 (Bittner Cr at Foreman Rd), google confirms the fix https://news.gov.bc.ca/releases/2020TRAN0099-001219, but latest in PSCIS is a culvert assessed as a barrier in 2014. 

I don't think office review barrier status should generally trump PSCIS barrier status, but in cases like this there needs to be a mechanism for it to do so.

**Comment by NewGraphEnvironment** [comment]
Well, that is incredibly serendipitous that you would comment on this just right now. About 20 minutes ago I was in a plane about to land in Prince George and I flew over Bittner Creek and thought. Hey I know that site assessed it.

https://www.newgraphenvironment.com/fish_passage_moti_2022_reporting/results-and-discussion.html#bittner-creek---196200

**Comment by smnorris** [comment]
So I have to ask... have you submitted the latest assessments to PSCIS?

**Comment by smnorris** [comment]
closing in favour of #521. 
- fixing matching of PSCIS crossings to FWA streams will continue to be case by case as required
- fixes to PSCIS itself to be noted in separate repository
