### ISSUE TITLE
reporting - update column names 

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#381]
`psql:bcfishpass/reports/general/sql/modelled_habitat.sql:106: ERROR:  column s.model_access_ch_co_sk does not exist`

**Comment by smnorris** [comment]
Not just column names, queries in `reports/general/sql` are all very dated.

Access queries should look more like this:
`WHERE s.barriers_ch_cm_co_pk_sk_dnstr = array[]::text[]`

**Comment by smnorris** [comment]
Issues like #388 point out the need for per-watershed group reporting to be generated with every model run and available for comparison/error checking.

**Comment by smnorris** [comment]
Consider also writing the report to a table in the database to enable easy comparisons of outputs over time. Or perhaps an archive of csvs. Diffing csv files is great for quick scans (especially if the IP model gradient segments get standardized)  but proper tracking of results should be added.

**Comment by smnorris** [comment]
This is done, but keeping open for feedback.
