### ISSUE TITLE
habitat model - include wetlands

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#42]
We want to multiply CO rearing habitat by 1.5x in wetlands to better account for it, but currently wetlands are not included at all in the spawning/rearing models - only rivers and `edge_type IN (1000,1100,2000,2300)` (single line bluelines, primary and secondary flow).

Are wetlands potential rearing habitat for all species, or just Coho?

**Comment by NewGraphEnvironment** [comment]
This was the issue that popped when I searched edge so I’ll just throw it here. Another vote for including edge codes within the parameters table is related to intermittent versus non-intermittent streams. With those codes in our pocket in theory users can tweak model outputs more easily to cater to intermittent versus intermittent streams. That would be of benefit for speeding/sorting queries related to field site prioritization.

**Comment by smnorris** [comment]
I'll reopen to keep this showing up in the list

**Comment by smnorris** [comment]
Adjusting IP models (beyond discharge and slope thresholds) via parameters would be nice but I think adjusting the IP queries as required for now is fine. I've accepted that reporting is different for each project and each project needs its own database. Perhpas the code repository can hold several different models and the user can choose which ones to drop in.

**Comment by NewGraphEnvironment** [comment]
Might be worth considering adding `edge codes` to `docs` and `read_me.md`s of habitat models (and access perhaps - my apologies if it is there already and I missed it).  Lots of species and model decision based nuances wrapped up in the edge codes and a link to fwa guide might be a good addition

![image](https://github.com/smnorris/bcfishpass/assets/46538103/a6ac1d68-3445-459c-9a61-95d0a870adfb)

https://www2.gov.bc.ca/assets/gov/data/geographic/topography/fwa/fwa_user_guide.pdf

**Comment by smnorris** [comment]
👍 Full documentation of spawning/rearing models (including this) is coming soon.
