### ISSUE TITLE
habitat model - spawning and rearing habitat refinements

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#46]
1. Rearing habitat downstream of spawning habitat does not need to actually be connected to the spawning habitat
2. Consider a maximum distance upstream from spawning habitat for connected rearing habitat to be valid
3. double line rivers meeting slope criteria should be coded as spawning habitat (due to general under-estimation of channel width by the channel width model on larger streams)
4. Investigate measuring channel width across river polygons if time allows
5. Include ALL potential rearing habitat DOWNSTREAM of spawning habitats (for that spp)
6. Include potential rearing habitat UPSTREAM of spawning habitat that is NOT connected IF slope between the rearing/spawning does not exceed 5% (with caveat that there may be an instream distance threshold applied in future)
7. Sockeye are different - model rearing habitat first and then add potential spawning habitat DOWNSTREAM of rearing lake where slope of segments between spawn and rear is <2% (again subject to a distance threshold TBD)

**Comment by smnorris** [comment]
3. double line rivers meeting slope criteria should be coded as spawning habitat (due to general under-estimation of channel width by the channel width model on larger streams)
4. Investigate measuring channel width across river polygons if time allows
5. Include ALL potential rearing habitat DOWNSTREAM of spawning habitats (for that spp)
6. Include potential rearing habitat UPSTREAM of spawning habitat that is NOT connected IF slope between the rearing/spawning does not exceed 5% (with caveat that there may be an instream distance threshold applied in future)
7. Sockeye are different - model rearing habitat first and then add potential spawning habitat DOWNSTREAM of rearing lake where slope of segments between spawn and rear is <2% (again subject to a distance threshold TBD)

**Comment by smnorris** [comment]
Sockeye update:

start with rearing habitat (i.e., lakes > 2 km2):
- Any tributary that flow into (I.e., upstream) a rearing lake and meets the spawning criteria:
  + Gradient <0.02
  + Width 2-50 m
- Any potential spawning habitat (criteria above)downstream of a rearing lake where:
  + Distance from lake outlet and stream segment is 3 km AND
  + slope between stream segment and lake outlet <5%

**Comment by smnorris** [comment]
Consolidating, more precisely: 

### channel width
- [ ] streams in river polygons meeting slope criteria should be coded as spawning habitat
- [ ] investigate measuring channel width across river polygons https://gist.github.com/smnorris/a94ee9dee346d692953b4431754c90b6

### general habitat model connectivity
- [ ] include ALL potential rearing habitat downstream of spawning habitats (not just connected rearing habitat) (for that spp)
- [ ] consider a maximum distance upstream from spawning habitat for connected rearing habitat to be valid
- [ ] include potential rearing habitat UPSTREAM of spawning habitat that is NOT connected IF slope between the rearing/spawning does not exceed 5% (with caveat that there may be an instream distance threshold applied in future)

### sockeye specific changes

Start model by identifying rearing habitat (potentially accessible lakes > 2 km2), then model spawning as:

- streams with gradient < .02 and channel width < 50m AND 
    + immediately upstream of lake OR
    + <3km downstream of lake AND slope between stream segment and lake outlet <5%

**Comment by smnorris** [comment]
Draft wrapped up with https://github.com/smnorris/bcfishpass/commit/4e3282b113fe88526998aedb06229661f900c59e but definitely needs review.

**Comment by NewGraphEnvironment** [comment]
Estimates of stream area (by individual species/life stage potential) using the newly devised width estimates would be very useful for estimating/visualizing potential habitat gains and allow comparison of m2/$1000 for remediation activities alongside linear m/$1000.

A good example of why this might be so useful in my opinion can be found by comparing a very large stream like Richfield Creek (est. channel_width = 12.5m) with a smaller system such as Coffin Creek (est. channel width 4.75m).  For the sake of an example, if we were to imagine that there were impassable falls 1km upstream of both target crossings, there would be far more potential for valuable habitat upstream of the crossing on Richfield Creek vs. Coffin Creek.  Photos of habitat in both systems can be viewed through the [interactive  map](https://newgraphenvironment.github.io/fish_passage_bulkley_2020_reporting/results-and-discussion.html).

**Comment by smnorris** [comment]
@NewGraphEnvironment - good comment but would be better over in #90

**Comment by smnorris** [comment]
Some QA is needed for rearing upstream of spawning.
See Schippers/Poryphyry (sp?)/Toboggan in BULK

**Comment by NewGraphEnvironment** [comment]
https://hillcrestgeo.ca/outgoing/fishpassage/projects/bulkley/FishPassage_093M.102.pdf (Porphyry) doesn't currently want to open in my browser.  Other maps do though...

**Comment by smnorris** [comment]
Review looks reasonable after applying https://github.com/smnorris/bcfishpass/commit/4d00f93be8049aae96c9ab1c8f9d97804fb98420

**Comment by NewGraphEnvironment** [comment]
> Some QA is needed for rearing upstream of spawning.
> See Schippers/Poryphyry (sp?)/Toboggan in BULK

having a look at Porphyryr and wondering why the habitat below barriers upstream of the Hwy is 0?

```
 porphyryr <- st_read(conn, query =  
"SELECT * FROM bcfishpass.crossings
   WHERE stream_crossing_id = '124487'")
```

**Comment by smnorris** [comment]
I'm guessing the calculation fails on that one because there aren't any barriers upstream.

**Comment by smnorris** [comment]
Actually, this deserves a new issue
