### ISSUE TITLE
consider adding `model_run_date_time` of changes to `bcfishpass.parameters_habitat_thresholds` to `bcfishpass.parameters_habitat_thresholds_log` 

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#490]
Maybe not worth it but going forward this would allow us to match documentation to time the output that was used in the product released was generated (if `model_run_id` was not recorded at production time).  

looked quickly to see if I could find where `parameters_habitat_thresholds_log` is generated so could potentially PR if seemed like a good idea.  Couldn't find it in 2 minutes. Maybe point to it here

For current runs this works great:

```
SELECT * FROM bcfishpass.parameters_habitat_thresholds_log
  WHERE model_run_id = (SELECT MAX(model_run_id)
  FROM bcfishpass.parameters_habitat_thresholds_log);
```

*edited: hmmm.. this assumes the latest logged run matches the current run

**Comment by smnorris** [comment]
The logging is hidden here, in the last script that gets called in the build: https://github.com/smnorris/bcfishpass/blob/main/model/02_habitat_linear/habitat_linear.sh
It should be in a separate script so it is findable.

If you know the date of your model run, you should be able to find the id, and thus the parameters via that join?

**Comment by smnorris** [comment]
So, for example - show the parameters used for the model run on April 8:
```
select p.*
from bcfishpass.parameters_habitat_thresholds_log p
inner join bcfishpass.log l
on p.model_run_id = l.model_run_id
where date_completed::date = '2024-04-08'
```

**Comment by NewGraphEnvironment** [comment]
amazing.  or vis versa with 

```
SELECT l.date_completed::date
FROM bcfishpass.log l
WHERE l.model_run_id = 9"

  date_completed
1     2024-04-08
```

thank you!
