### ISSUE TITLE
Use observed spawning (not just modelled) when modelling rearing

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#495]
From @nickw-CWF 
>I was looking at some systems in the Lower Nicola, and noticed that there are some stream segments that seem like they should be flagged as ST habitat that aren’t. I know we had discussed removing the MAD parameter requirements for all species habitat in the Lower Nicola, but even if this hasn’t been implemented yet there are still segments that seem to meet the parameter requirements that aren’t being flagged as habitat.
 
>For example, linear_feature_id = 701760481
>gradient = 0.0333
>mad_m3s = 0.13296
 
>Which are within the rearing thresholds of < 0.074 and 0.02-60, respectively.

**Comment by smnorris** [comment]
That is an interesting issue. 

For that segment, the discharge and gradient do not meet spawning model thresholds - there is not enough discharge. But FISS indicates there is spawning at that location, so we code it as spawning (50m on each side of the FISS point). 

As noted, the stream does meet rearing criteria and rearing can be coded on spawning segments.
But... the rearing model currently doesn't recognize spawning that comes from `data/user_habitat_classification.csv`, it only looks at modelled spawning.

I'd call this a bug, we should probably model rearing on all spawning.

**Comment by nickw-CWF** [comment]
Thanks for looking into this Simon. I would agree that we want to model connectivity based on all spawning data.
