### ISSUE TITLE
include crossings in non-wcrp watersheds in crossings_wcrp_vw?

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#505]
From @nickw-CWF 

>I’ve been looking at some data and there appears to be an issue with the CO rearing calculations for features in the crossings_wcrp_vw layer - values are being assigned NULL where there should be rearing habitat.
 
>For example, 126316:
In crossings_wcrp_vw, co_rearing_km = NULL
In crossings_vw, co_rearing_km = 92.0277288106163
 
>And looking at the streams_vw, there are streams upstream of this barrier modelled as rearing habitat.

**Comment by smnorris** [comment]
@nickw-CWF  - values are null for this crossing because this crossing is in the `WILL` watershed, not currently included in the WCRP table.
I can update so that WCRP metrics are included for all crossings (or perhaps only include crossings in WCRP watersheds in the view, but this seems less useful)

**Comment by smnorris** [comment]
@nickw-CWF - since you're working with that crossing I'll presume that we want non-WCRP watershed crossings in this view.

But this gets tricky when combined with #480 - with that fix, we now force reporting to be only on target species.

So if a watershed is not listed in the WCRP table, all spawing/rearing columns should now be null. 

A workaround could be to add any watershed of interest to the wcrp table?

**Comment by nickw-CWF** [comment]
I'm happy with adding any watersheds of interest to the wcrp control table.
