### ISSUE TITLE
tag reviewed crossings in crossings_vw

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#559]
https://github.com/NewGraphEnvironment/fpr/issues/93
Join to `user_modelled_crossing_fixes` on materialized view creation so user can quickly tell which crossings have had some kind of office review.
I was originally thinking a boolean column, but just pulling the `review_date` in is simpler.

**Comment by smnorris** [comment]
@NewGraphEnvironment Update has been applied to the `_dev` database. 
I'd prefer to wait till next tagged release (with any additional updates) to apply to primary db, but if this is a priority let me know and I can merge PR and tag this update.

**Comment by NewGraphEnvironment** [comment]
we could use this update right away if possible as we are now actively planning for field early september. it will save us a bunch of time...
