### ISSUE TITLE
Aitken Creek has no modelling info

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#565]
Can't see why....

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/a74f52ad-e7eb-4d97-94fa-12dfbf5fd441">

`linear_feature_id` = 17088471

**Comment by smnorris** [comment]
What is missing, from which table?
Which copy of the data are you using?

Via db `bcfishpass` on the New Graph/Poisson server things seem ok in `bcfishpass.salmon_vw` - what kind of problem should I be looking for?
![Screenshot 2024-09-09 at 8 57 48 AM](https://github.com/user-attachments/assets/0e40aa9a-22fd-46ee-ad01-5bdf1ee00df1)

**Comment by NewGraphEnvironment** [comment]
looks like the version of `bcfishpass.streams` I was looking at is ancient.  My bad.  I will update the file. Sorry

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/8a6abb0b-b395-4170-a7b1-20b28c0fb74f">

**Comment by smnorris** [comment]
no prob, glad it was a simple thing
