### ISSUE TITLE
add code for generating gradient barriers

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#6]
Upgrade old python 2.7 code to python 3, or migrate completely to sql

**Comment by smnorris** [comment]
Code to create gradient barriers is in here:
https://github.com/smnorris/FWAToolsArchive/blob/main/fwatools/stream.py#L421

To create gradient barriers for a given stream (blue_line_key):
```
from FWATools import FWA
from FWATools import Stream 

wsg = 'COWN'
blueLineKey = 354101673
windowSize = 100
slopeThreshold = [.03, .05, .08, .15, .22, .30]


# load stream profile
stream = Stream(blueLineKey, FWA, wsg)

# generate gradient barrier events
# ie, linear events along stream where slope > than given value
# the events are stored as list of tuples:
# [(threshold, blueLineKey, wsCode, localCode, toLocalCode, fromMeasure, toMeasure, fromElev, to Elev, length, slope)]
events = stream.get_multi_gradient_barrier_events(windowSize, slopeThreshold)
eventList = []
if events:
    for e in events:
        eventList.append(e)

# append watershed group code to the end of each tuple
if eventList:
    sql = """INSERT INTO my_table
                 (threshold,
                  blue_line_key,
                  fwa_watershed_code,
                  local_watershed_code,
                  upstream_local_code,
                  downstream_route_measure,
                  upstream_route_measure,
                  length_metre,
                  from_elevation,
                  to_elevation,
                  gradient,
                  watershed_group_code)
              VALUES (?,?,?,?,?,?,?,?,?,?,?,'{wsg}')
           """.format(wsg=wsg)
    FWA.db.execute_chunks(sql, eventList, 500)
```

**Comment by smnorris** [comment]
This new script generates the breaks and fixes #7 (but outputs still need QA):
https://github.com/smnorris/bcfishpass/blob/gradientbreaks/01_prep/gradient_barriers/sql/gradient_barriers.sql

@NewGraphEnvironment @nickw-CWF @captainmarmot
The method is *almost* the same - the script starts at the bottom of each distinct `blue_line_key` and considers each vertex on the stream. But now instead of calculating slope between a given vertex and the next vertex at least 100m along, the slope is calculated between the initial vertex and a point on the stream exactly 100m distant.

The results won't be much different and the added precision is not necessary for fish passage - but it was an easy modification and it seems preferable that the distance along which the grade is calculated is consistent. Down side is that there are more points, but that shouldn't matter.

**Comment by smnorris** [comment]
The best way to do it is probably to take the 100m slope at 50m intervals, regardless of where vertices are. I might try that as well. I think it would be just a little bit trickier than existing query because of having to deal with the end points.

**Comment by NewGraphEnvironment** [comment]
Very cool. Nice work!


Should line 39 read

`WHEN gradient >= .2 AND gradient < .30 THEN 20 ` 

rather than

`WHEN gradient >= .2 AND gradient < .25 THEN 20`

?

**Comment by smnorris** [comment]
Good eye. I've fixed that locally but am still not sure if I want to include all of .10/.15/.20/.25/.30 or just .15/.20 that we are using right now and add the rest as needed.

**Comment by NewGraphEnvironment** [comment]
As you know, .30 is extremely relevant for stream classifications and barrier hunting for any watershed with potential bull trout presence.   They can all be really useful for one thing or another though in my opinion.  I think I have come across some literature about some applications for ~0.5.... I'll look into it.

**Comment by smnorris** [comment]
Yes, I think I'll just generate every step 5-30. It will be a huge table but that isn't really a big deal, generating the barrier tables from it filters the results down as needed.

**Comment by smnorris** [comment]
This is the record count when running every gradient from 5-30 at 5% intervals:
```
select gradient_class, count(*) from bcfishpass.gradient_barriers group by gradient_class;
 gradient_class |  count
----------------+---------
              5 | 1790760
             10 | 1845462
             15 | 1887282
             20 | 1885062
             25 | 1856432
             30 | 1633786
```
A lot of records. But because the table is so basic it is only ~1/4 the size (542MB) of the existing gradient_barrier table that includes geoms and other additional (redundant) fields.

**Comment by smnorris** [comment]
When using these new gradient breaks as barriers in the existing WCRP models, length of potentially accessible habitat is reduced slightly, as expected (GBa=old gradient breaks, GBb=new gradient breaks, all numbers are km):

| watershed_group_code|potentially_accessible_GBa | potentially_accessible_GBb | Percent difference |
|--------|-------|--------|--------|
| BULK   | 6051  |  6017  |  -0.56% |
| ELKR   | 3782  |  3760  |  -0.58% |
| HORS   | 1077  |  1064  |  -1.21% |
| LNIC   | 2314  |  2287  |  -1.17% |
| TOTAL  | 13224 |  13128 |  -0.73% |

**Comment by NewGraphEnvironment** [comment]
Looks like you just sharpened the swords. ⚔️

**Comment by smnorris** [comment]
Pretty much. The result does look slightly tidier. Almost ready to merge into main.

**Comment by smnorris** [comment]
fixed with https://github.com/smnorris/bcfishpass/commit/e1a1d68bc1c0d6237b47a225e9c72b82488a038a
