### ISSUE TITLE
data - load misc new LNIC barriers

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#68]
For these points, translate UTMs into positions on the stream network and add to https://github.com/smnorris/bcfishpass/blob/main/01_prep/05_other/data/misc_barriers.csv
[LNIC_Barriers.txt](https://github.com/smnorris/bcfishpass/files/5934198/LNIC_Barriers.txt)

**Comment by smnorris** [comment]
@njohanley - Can you take care of this?

**Comment by njohanley** [comment]
Sure thing!

**Comment by smnorris** [comment]
FYI I don't think the crossing id in the file corresponds to anything on our system, you can probably just ignore that

**Comment by njohanley** [comment]
Sounds good
