### ISSUE TITLE
`total_lakereservoir_ha` not shown in crossings table

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#69]
Besides the fact that it is Saturday, I don't need any immediate action on this to keep plugging away (I have hand bombed McDowell into the reporting). Not sure if there will be a bunch of other sites that will have the same issue, and guessing you want to know so I will document here.  

McDowell Creek (`stream_crossing_id` = 58159) drains McDowell Lake, Lacroix Creek (58161) drains Round lake and Tyhee Ck (123446) drains Tyhee Lake. All three of these PSCIS crossings are matched correctly to modelled crossings in `bcfishpass.crossings`.

The `bcfishpass.crossings` table does not display any lake areas upstream of the first two crossings (see query below).   

I used Round Lake as a QA as it shows as `POTENTIALLY ACCESSIBLE - PSCIS BARRIER DOWNSTREAM` in the `bcfishpass.streams` layer.  Upstream lake area does not show up there either.  Interestingly, Tyhee Lake  `total_lakereservoir_ha` does show up....

`SELECT a.total_lakereservoir_ha 
           FROM bcfishpass.crossings a
           WHERE stream_crossing_id IN (58159,58161,123446)`

total_lakereservoir_ha
1                   0.00
2                   0.00
3                 372.72

**Comment by smnorris** [comment]
Likely a duplicate of #20

Haven't looked too closely at it yet because I was adding the upstream area columns directly to the fwa streams table to support the channel width modelling.

**Comment by NewGraphEnvironment** [comment]
:metal:

**Comment by smnorris** [comment]
This should be fixed now, let me know if you're still seeing zeros where there shouldn't be.
