### ISSUE TITLE
waterfalls - support barrier status updates to control load to bcfishpass.barriers_falls

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#78]
Currently, the access model loads four specific falls in HORS to the bcfishpass.barriers_falls table, direct from the FISS falls table https://github.com/smnorris/bcfishpass/blob/main/02_model/sql/barriers_falls.sql

Separately, [`waterfalls.sql`](https://github.com/smnorris/bcfishpass/blob/main/02_model/sql/waterfalls.sql)
- loads all FISS waterfalls to `bcfishpass.waterfalls`
- loads all CWF additional waterfalls to `bcfishpass.waterfalls` (note that this data includes some FISS data, I can't remember why they got duplicated or if there were any changes to the FISS info)
- break `bcfishpass.streams` at all the waterfalls in `bcfishpass.waterfalls` 

But nothing is done with `bcfishpass.waterfalls`.

We'd like to maintain a barrier status for the waterfalls, allowing load of select records into `barriers.falls` to be used as definite barriers.

To do this (and still support ongoing load of additional features directly from FISS as it gets updated):

1. add `barrier_ind` to the CWF compiled falls data https://github.com/smnorris/bcfishpass/blob/main/01_prep/05_other/data/falls.geojson

2. FISS data is trickier, @NewGraphEnvironment noticed that the `fish_obstacle_point_id` is not stable, we may not be able to manually flag barriers using this id. Using `blue_line_key` / `downstream_route_measure` would work but that is fussier.

Note that in the FPTWG model, barrier status is simply True for FISS falls >= 5m

**Comment by NewGraphEnvironment** [comment]
I can confirm that the file has indeed been unstable. I cross referenced a version downloaded today with an old shapefile version I dug up with a file `date_modified` tag of 2017-01-31.  I used this [script](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/blob/master/R/test-fiss_obstacles_pnt_sp.R) in the test. The results are [here](https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/blob/master/data/extracted_inputs/fiss_obstacle_qa.csv).

:eyes:

**Comment by smnorris** [comment]
Interesting that the short name has changed. If the data model changed it might be safe to presume that the new ids are stable enough for now going forward. I'll give it a couple more days to see what Gord W and the Province say but I think we can probably just go ahead with creating a id based lookup and deal with it later if something changes.

**Comment by NewGraphEnvironment** [comment]
Ya. Should be good to go in theory but I’m sure there was an issue with that falls in the Morrissey amd that dataset was less than a year old so it does make sense to follow up  with the province I think. Thanks for doing that.

**Comment by NewGraphEnvironment** [comment]
So to add non-FISS falls so they impact the model results we modify [misc_barriers_definite.csv](https://github.com/smnorris/bcfishpass/blob/main/01_prep/05_other/data/misc_barriers_definite.csv)?

For the `bcfishpass.waterfalls` does it make sense to load it in, make barrier status True for FISS falls >= 5m (I might even suggest 3m as 2m is the highest possible for any species to ascend - if the rock is actually vertical as I believe a "falls" should be). Then, when updating the FISS layer we archive the previous layer and run a quick check to see that the keys are stable.  If there was an issue we could proactively derive the `blue_line_key `/ `downstream_route_measure ` and rematch?

**Comment by smnorris** [comment]
> So to add non-FISS falls so they impact the model results we modify misc_barriers_definite.csv?
Currently yes but I will move things around a bit, it makes sense to have a falls table with the barrier status that feeds directly into `bcfishpass.barriers_falls` rather than loading into misc/other

> make barrier status True for FISS falls >= 5m (I might even suggest 3m as 2m is the highest possible for any species to ascend
Making all FISS falls > 5m a definite barrier is my plan for all watersheds outside CWF target watersheds

> Then, when updating the FISS layer we archive the previous layer and run a quick check to see that the keys are stable. If there was an issue we could proactively derive the blue_line_key / downstream_route_measure and rematch?
Yes, that was my thought too although I hadn't thought to add the check, I was just going to wait until it failed 😬

**Comment by NewGraphEnvironment** [comment]
Why not have FISS falls > 5m be definite barriers for the BULK?  CWF is going through them all by hand and adding a flag as a QA and they will be loaded at a later date? If not, for falls such as the one on Richfield, how do I get the falls to impact the symbology on our maps? (That is not really the best example since there is another barrier on Richfield much farther down from that kml from Jonathan than I can add to `misc_barriers_definite.csv` - but you get the idea...).

Maybe a script to QA the FISS obstacles key check into `bcfishpass` isn't necessary at this point but might not be a bad idea to keep some sort of archive of the FISS obstacles layer for a little bit in case we see a repeat of what happened with the Morrissey? I now have a version of the layer from January 1, 2021 with a `record_last_modified` column  (more like `date_downloaded` in reality it seems) archived on my machine and can leave it there.

**Comment by smnorris** [comment]
Yes, classifying FISS falls >=5m in BULK and elsewhere as barriers and including them in the model makes sense to me.  And I'm pretty sure this is the way we'll go for target watersheds, I opened this issue based on CWF request. 
Let me reorganize the falls and the misc/other tables slightly - there will be a mechanism to get the maps the way we want them.

I think the reason falls initially fell out of the barrier mix was because we thought the gradient barriers would catch most of them anyway.

FISS issues will get taken care of in bcfishobs repo, I'll open an issue there for the archive.

**Comment by nickw-CWF** [comment]
Hi guys,

Finally catching up on this. My two cents on some of the points above:
- Agreed adding a `barrier_ind` field for waterfalls is the way to go. I am happy to have FISS falls >= 5m be classified as barriers in the target watersheds.
- I would prefer if waterfalls get tracked and loaded through a table separate from [misc_barriers_definite.csv](https://github.com/smnorris/bcfishpass/blob/main/01_prep/05_other/data/misc_barriers_definite.csv). I think there is value in maintaining a separate waterfalls layer and associated fix table moving forward. I have a few falls updates from Steve in the Horsefly.
- I'll leave the setup of id lookups/QA checks to both of your expertise on the best way to do so

**Comment by smnorris** [comment]
Pretty much done here: https://github.com/smnorris/bcfishpass/tree/falls/01_prep/05_falls

- add any new falls to `falls_other.geojson`, try and get them close to the correct stream, table has a `barrier_ind` field 
- FISS falls default to barrier if >=5m, and barrier status can be controlled by editing this https://github.com/smnorris/bcfishpass/blob/falls/01_prep/05_falls/data/falls_fiss_barrier_ind.csv

I'd consider changing `falls_other.geojson` to a csv with blue_line_key and measure to standardize with the other files and force the user to do the stream matching manually. Not sure if that would actually help with accuracy.

**Comment by smnorris** [comment]
I find editing `falls_other.geojson` nice in QGIS but more of a pain overall.  I'll convert to csv with measures to match all the other files. 

Because there is no ID in FISS data that we can use to consistently match a falls to a stream, I think we'll have to add any FISS falls of interest that are >200m from a stream to `falls_other`. There is already one in there. If there are FISS falls that get matched to the wrong stream we can tag them as `barrier_ind` = False and if needed, add them to the correct stream in `falls_other`. A messy process but it should work.

**Comment by NewGraphEnvironment** [comment]
Good stuff. Thank you. :tropical_fish:

**Comment by NewGraphEnvironment** [comment]
So... for the falls in the Bulkley that we got from Jonathan, there are a bunch of points that are "suspected" locations (in yellow) of falls or rapids that he has lined up for future confirmation . The confirmed barriers are green.  I can either:

1. Add a column to the [falls_other.csv ](https://github.com/smnorris/bcfishpass/blob/main/01_prep/05_falls/data/falls_other.csv) such as `confirmed` and flag it `TRUE` or `NA` or
2. Remove the non-confirmed points.

I think maybe just flagging them is a better plan as the file can be used for follow up in the future.

Also wondering about additional columns for the falls_other.csv.  Should I maybe add a utm_zone, utm_easting, utm_northing to the file so that others can simply input coordinates rather than running `fwapg::fwa_indexpoint` to get `blue_line_key` and `downstream_route_measure`?

I have falls to add so could doll it up then PR today or tomorrow morning.

**Comment by smnorris** [comment]
New field for additional followup fine by me if you want - but there is already `barrier_ind` - anything that does not have `barrier_ind = T` is currently ignored anyway

Prefer not to have coordinates in the file unless there is a need. My thinking on this is that it forces the user to think about what stream they actually want the falls to block. Running `fwapg::fwa_indexpoint` doesn't seem necessary unless you have dozens of falls - getting the blue_line_key by clicking on the stream in QGIS is easy. And measures don't have to be exact, they just have to be on the right side of any tribs or crossings - and that is easy if you use the `bcfishpass.streams layer`.

**Comment by NewGraphEnvironment** [comment]
ok.  Right,  `barrier_ind = T`.  Forgot about that one.  That is what I will use for the confirmed and new barriers.  Although, it seems like maybe all the falls are showing on the [webmap](https://www.hillcrestgeo.ca/projects/cwf_wcrp/) currently?

All good for the `blue_line_key ` and `downstream_route_measure` thing. Makes sense. I didn't realize it was that easy to derive with the point and click. Hadn't looked at it. Easy peasy.

**Comment by smnorris** [comment]
Yep - all waterfalls are currently shown for the planning teams to review. 
But only the ones marked as barriers (or over 5m) have any effect.
Web map is still very draft at the moment.
