### ISSUE TITLE
reporting - report on habitat area

### ISSUE THREAD

**Issue by smnorris** [smnorris/bcfishpass#90]
As @NewGraphEnvironment suggested, we have modelled channel width for the target watersheds, we could report on habitat area rather than / in addition to linear measurements. This is something @CaptainMarmot has had in mind for some time. And resolves the issue of trying to fudge rearing lakes/wetlands into linear measurements.

eg 
```
ch_spawning_ha
ch_rearing_ha
ch_spawning_belowupstrbarriers_ha
ch_rearing_belowupstrbarriers_ha
co_spawning_ha
```
etc etc

For streams, area = length of channel * modelled width.

**Comment by NewGraphEnvironment** [comment]
🦃

**Comment by smnorris** [comment]
Even if we don't calculate stream areas, I do need to add these two upstream area summaries to crossings table / report.sql at a minimum:

- `co_rearing_ha` - area of wetlands used as coho rearing upstream 
- `sk_rearing_ha` - area of lakes used as sockeye rearing upstream
