### ISSUE TITLE
provide requirements file/spec

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#97]
loading up is going well.  

does zonalstats need to be loaded to the conda `bcfp` env perhaps?

Did a `pip install zonalstats` and reran `./mean_annual_precip.sh` from `01_prep/04_channel_width` but still getting 

`psql -t -c 'SELECT
  ST_AsGeoJSON(t.*)
FROM
  (
    SELECT DISTINCT
      watershed_feature_id,
      watershed_group_code,
      geom
    FROM whse_basemapping.fwa_watersheds_poly
    WHERE watershed_group_code IN ('\''BULK'\'','\''LNIC'\'','\''HORS'\'','\''ELKR'\'','\''MORR'\'')
  ) as t'
+ parallel --pipe 'rio -q zonalstats       -r mean_annual_precip.tif       --prefix '\''map_'\'''`
+ jq '.features[].properties | {watershed_feature_id: .watershed_feature_id, watershed_group_code: .watershed_group_code, map: .map_mean}'
+ jq --slurp .
+ in2csv -f json
+ psql -c '\copy bcfishpass.mean_annual_precip_wsd_load FROM STDIN delimiter '\'','\'' csv header'
./mean_annual_precip.sh: line 33: jq: command not found
./mean_annual_precip.sh: line 34: jq: command not found
./mean_annual_precip.sh: line 35: in2csv: command not found
COPY 0
Usage: rio [OPTIONS] COMMAND [ARGS]...
Try "rio --help" for help.

maybe i need to reload `rasterstats` somehow so the script can access it perhaps? Thoughts?

**Comment by NewGraphEnvironment** [comment]
of note I don't have the csv output from `bcfishobs`.  Guessing that doesn't matter though...

**Comment by NewGraphEnvironment** [comment]
hmm. I wonder if my python version isn't playing nice... I wonder if I should try removing my virt env, uninstalling conda and starting again with [conda 3.7.3](https://repo.anaconda.com/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh)?

python                    3.9.2           hffdb5ce_0_cpython    conda-forge
rasterio                  1.2.1            py39h63973eb_2    conda-forge
rasterstats               0.14.0                     py_0    conda-forge

Also, I have looked around quite a bit (ineffectively perhaps) but I can't seem to figure out where the test data would be for rasterio or rasterstats.... Seems like there is some somewhere because of examples in the help files (ex. tests/data/slope.tif) but maybe I need to get it from elsewhere?

**Comment by smnorris** [comment]
I've added `rasterstats` to the requirements outline in the README.
There should be an actual `requirements.txt` or `environment.yml` and I should actually use it in development so dependencies don't get missed.
Conda will probably handle the `parallel` dependency too but since you're on WSL installing that one is easy.

- not sure why you're Python version would have issues
- I don't think rasterio/rasterstats would automatically install their test data, you'd have to clone the repo to run tests, see their docs

**Comment by NewGraphEnvironment** [comment]
`conda install csvkit` 
`conda install jq`

as well?

Ya, I tried with `python 3.7` and `rasterstats` still will not plug into `rasterio` as it keeps giving me No such command "zonalstats"

When you type `rio --help` does it list `zonalstats` as a command?

**Comment by smnorris** [comment]
Yes to csvkit and jq

Not sure what is going on with `rasterstats`, I can import it in python (3.8.5) but the command I used `rio zonalstats` I get the same error. I don't think it is your issue, something isn't quite right.

```
$ rio zonalstats
Usage: rio [OPTIONS] COMMAND [ARGS]...
Try 'rio --help' for help.

Error: No such command 'zonalstats'.
```

**Comment by smnorris** [comment]
Above test was on my system Python. Setting up a new conda env `bcfp` as in the README and `zonalstats` is there and accessible.

```
(bcfp)
snorris at Matchlee in ~/projects/repo/bcfishpass on main [!?]
$ rio --help
Usage: rio [OPTIONS] COMMAND [ARGS]...

  Rasterio command line interface.

Options:
  -v, --verbose           Increase verbosity.
  -q, --quiet             Decrease verbosity.
  --aws-profile TEXT      Select a profile from the AWS credentials file
  --aws-no-sign-requests  Make requests anonymously
  --aws-requester-pays    Requester pays data transfer costs
  --version               Show the version and exit.
  --gdal-version
  --help                  Show this message and exit.

Commands:
  blocks      Write dataset blocks as GeoJSON features.
  bounds      Write bounding boxes to stdout as GeoJSON.
  calc        Raster data calculator.
  clip        Clip a raster to given bounds.
  convert     Copy and convert raster dataset.
  edit-info   Edit dataset metadata.
  env         Print information about the Rasterio environment.
  gcps        Print ground control points as GeoJSON.
  info        Print information about a data file.
  insp        Open a data file and start an interpreter.
  mask        Mask in raster using features.
  merge       Merge a stack of raster datasets.
  overview    Construct overviews in an existing dataset.
  pointquery  Queries the raster values at the points of the input GeoJSON...
  rasterize   Rasterize features.
  rm          Delete a dataset.
  sample      Sample a dataset.
  shapes      Write shapes extracted from bands or masks.
  stack       Stack a number of bands into a multiband dataset.
  transform   Transform coordinates.
  warp        Warp a raster dataset.
  zonalstats  zonalstats generates summary statistics of geospatial raster...
```

**Comment by smnorris** [comment]
And this is with Python 3.9.2, the default pulled in by conda.

**Comment by NewGraphEnvironment** [comment]
Figures. Things were going a bit too well there for a while. 

Ok. Sounds like it should work out of the box and isn't for me in multiple environments.  I wonder if my version of conda might have anything to do with it?  I wouldn't think it would matter but this is what I used - `https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh`

I wonder if I should be using a windows one. Seems like an odd thing but in [the reference I used to set up my wsl2](https://towardsdatascience.com/data-science-on-windows-subsystem-for-linux-2-what-why-and-how-77545c9e5cdf) it shows 

```
# To install Anaconda for Python 3
wget https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
sh ./Anaconda3-2020.02-Linux-x86_64.sh
# To install Miniconda for Python 3
 
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
sh ./Miniconda3-latest-Windows-x86_64.exe`
```

I figured since there was a Linux version for Anaconda and a windows version for Minconda that the lower one must have been an error.  If I were to start with a fresh conda install which would you recommend?

**Comment by smnorris** [comment]
This is not a path I have walked down, you're going to have to experiment.

I don't understand why that ref would point to Anaconda for linux and miniconda for windows. Definitely try the linux version.

**Comment by NewGraphEnvironment** [comment]
ya.  I've definitely been experimenting. I'll stick with the linux versions.  i'll try uninstalling conda and reinstalling with anaconda. I'm a bit concerned its my Linux kernel and not the easy stuff at all. Its such a lovely command as written.  I don't want to try to go around it then make it sloppy and run into something else on the next script. Oh jeez.

**Comment by smnorris** [comment]
All that stuff is just for the precip, it isn't a big deal as long as you have python / postgres working nicely.
I doubt it is anything OS related.

**Comment by NewGraphEnvironment** [comment]
right. python and postgres do run and I can get the python example to run for `rasterstats`.  I should probably damage control a bit then and not put too many more hours into this if going around isn't going to be too crazy a detour. I'll try a couple things look at how going around might look.  I might try to get some sort of interpreter set up.  vim seems pretty tricky.

**Comment by NewGraphEnvironment** [comment]
i ran into issues editing files with rstudio that were on the mounted drive... I think maybe I need rstudio to be installed into `wsl2` and open it in there. Everything seems a bit tricky because all the references I find seem to tell me different things. I'm probably doing things super extra inefficiently. 

I should just be able to install `rstudio` with `Anaconda` into the `wsl2 ` and run on that right?  I'll try that unless you think that doesn't make sense. One day I'm going to look back at this and laugh. A bit stressful right now though...

**Comment by NewGraphEnvironment** [comment]
Well took me all day and somehow lost git and got it back (mostly) but it was your little test this morning that helped me find the issue.  I almost gave up and started trying to hack your perfect precip processing code...

I had set up my virt env inside of the `conda (base)` environment so it wasn't putting things together correctly.  Ok.  Onward. Thanks Simon!
