### ISSUE TITLE
Load upstream watershed, lake, reservoir, wetland to fwa_stream_networks_sp before channel_width scripts?

### ISSUE THREAD

**Issue by NewGraphEnvironment** [smnorris/bcfishpass#99]
First of all. These scripts are off the hook amazing. Incredible work. Razor-sharp 🔪 .

I wonder if I might be missing something but -  are there variables that should load to the `whse_basemapping.fwa_stream_networks_sp` table before building `bcfishpass.channel_width_measured`  with `channel_width_measured.sql` in [`01_prep/04_channel_width/channel_width-measured.sh`](https://github.com/smnorris/bcfishpass/blob/main/01_prep/01_modelled_stream_crossings/modelled_stream_crossings.sh)?

first error thrown on script on fresh database build is:
```
psql:sql/channel_width_measured.sql:163: ERROR:  column b.upstream_lake_ha does not exist
LINE 7:     max(b.upstream_lake_ha) AS upstream_lake_ha,
```
this refers to this section of the script:

```
WITH update_vals AS
(
  SELECT
    a.wscode_ltree,
    a.localcode_ltree,
    max(b.upstream_area_ha) AS upstream_area_ha,
    max(b.upstream_lake_ha) AS upstream_lake_ha,
    max(b.upstream_reservoir_ha) AS upstream_reservoir_ha,
    max(b.upstream_wetland_ha) AS upstream_wetland_ha
  FROM bcfishpass.channel_width_measured a
  INNER JOIN whse_basemapping.fwa_stream_networks_sp b
  ON a.wscode_ltree = b.wscode_ltree
  AND a.localcode_ltree = b.localcode_ltree
  AND a.watershed_group_code = b.watershed_group_code
  GROUP BY a.wscode_ltree, a.localcode_ltree
)
```

**Comment by smnorris** [comment]
Yes, I added those columns in `fwapg` https://github.com/smnorris/fwapg/tree/main/extras - you'll need to run the extras:
`python add_upstream_area_ha.py`

**Comment by NewGraphEnvironment** [comment]
Is it just my system or should python add_upstream_area_ha.py be taking like 18hrs to get a little over halfway through the watershed groups?  Wondering if the slowness is related to the fact that my hardrive is really full.  That probably doesn't help but I wonder how long it takes you to run the script.....

**Comment by smnorris** [comment]
Not just you - most of the stuff in `extras` is very very slow - it isn't optimized the way the main stuff is.  
That sounds like it is a bit slower than my system but I have to run it overnight for sure.

**Comment by smnorris** [comment]
Because it only has to be run once (per FWA load) I can't be bothered to improve it - it will always be slow, the calculation is very expensive - find all watershed polygons upstream for every single line segment in BC. There is probably a smart way to do it fast but I haven't thought of it.

**Comment by NewGraphEnvironment** [comment]
Thanks. Ya, its not surprising to me that it takes a while.  Lots of work going on there!  I'm trying to clean up my old databases now to create a bit of space. It's probably quite hard on the hardware right now!
